---
title: <center></font><font size="6"><br><b>Bioacoustic Analysis in R</b></font></center><br>
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->
<br>

<center><font size="5"><b><a href="https://tropicalstudies.org/">Organization for Tropical Studies</a><br></b></font></center><br>


<center><font size="4">March 14 - 18, 2022</font></center>

&nbsp; 

The study of animal acoustic signals is a central tool for many fields in behavior, ecology, evolution and biodiversity monitoring. The accessibility of recording equipment and growing availability of open-access acoustic libraries provide an unprecedented opportunity to study animal acoustic signals at large temporal, geographic and taxonomic scales. However, the diversity of analytical methods and the multidimensionality of these signals posts significant challenges to conduct analyses that can quantify biologically meaningful variation. The recent development of acoustic analysis tools in the R programming environment provides a powerful means for overcoming these challenges, facilitating the gathering and organization of large acoustic data sets and the use of more elaborated analyses that better fit the studied acoustic signals and associated biological questions. The course will introduce students on the basic concepts in animal acoustic signal research as well as hands-on experience on analytical tools in R.


### Objetive

Training biological science students and researchers in the detection and analysis of animal sounds in R. Specifically, it seeks to familiarize participants with computational tools in the R environment aiming at curating, detecting and analyzing animal acoustic signals, with an especial focus on quantifying fine-scale structural variation. The course will introduce the most relevant acoustics concepts to allow a detailed understanding of the metrics used for characterize acoustic signals. It will also guide participants through a variety of R packages for bioacoustics analysis, including seewave, tuneR, warbleR, PhenotypeSpace and baRulho. 


 
Download [this folder with example sound files and annotations](https://www.dropbox.com/sh/9b0ol3xw4nuqu7q/AAAojzPMZv09WUmq8ucM72x7a?dl=0) into your course project directory.


---

### Program / tutorials
<font size="3.5">

**General bioacoustics concepts**

  - History and development
  - Analytical workflow in bioacoustics research

**Basic R concepts** <a href="https://github.com/maRce10/BOKU_bioacoustics_2022/blob/master/tutorials/R-basics.html" class="btn btn-warning btn-xs" role="button">R basics</a>

- Object types in R 
- Subsetting
- Style matters
- R documentation

**What is sound?** <a href="https://www.dropbox.com/s/yw3vfa5olbocm8q/Sound_in_R.html?dl=0" class="btn btn-warning btn-xs" role="button">Sound</a>
  
  - Sound as a time series
  - Sound as a digital object
  - Acoustic data in R
  - 'wave' object structure 
  - 'wave' object manipulations
  - additional formats
  
  
  **Building spectrograms** <a href="https://marceloarayasalas.weebly.com/uploads/2/5/5/2/25524573/spectrograms.html" class="btn btn-warning btn-xs" role="button">Building spectrograms</a>
  
  - Fourier transform
  - Building a spectrogram
  - Characteristics and limitations
  - Spectrograms in R

**Package seewave**  <a href="https://marceloarayasalas.weebly.com/uploads/2/5/5/2/25524573/seewave.html" class="btn btn-warning btn-xs" role="button">seewave</a>

  - Explore, modify and measure 'wave' objects
  - Spectrograms and oscillograms
  - Filtering and re-sampling
  - Acoustic measurements

**Annotation software** <a href="https://www.dropbox.com/s/7l921d584oh6djq/Annotations.html?dl=0" class="btn btn-warning btn-xs" role="button">annotations</a>

  - Raven / audacity
  - Open and explore recordings
  - Modify-optimize visualization parameters 
  - Annotate signals

**Intro to warbleR** <a href="https://ndownloader.figshare.com/files/27066653" class="btn btn-warning btn-xs" role="button">Intro to warbleR</a>

  - Intro to warbleR
  - Selection tables 
  - Extended selection tables
  - Selection table manipulation
  - warbleR functions and the bioacoustics analysis workflow

**Automatic detection** <a href="https://ndownloader.figshare.com/files/27242135" class="btn btn-warning btn-xs" role="button">Automatic detection</a>

  - Detection using amplitude, frequency, and time filters (`auto_detec()`)
  - Detection using cross-correlation (`cross_correlation()`)
  - Frequency range detection (`freq_range()` and `freq_range_detec()`)

**Quantifying acoustic signal structure**  <a href="https://ndownloader.figshare.com/files/27232883" class="btn btn-warning btn-xs" role="button">Quantify structure</a>

  - Spectro-temporal measurements (`spectro_analysis()`)
  - Parameter description
  - Harmonic content
  - Cepstral coefficients (`mfcc_stats()`)
  - Cross-correlation (`cross_correlation()`)
  - Dynamic time warping (`freq_DTW()`)
  - Signal-to-noise ratio (`sig2noise()`)
  - Inflections (`inflections()`)
  - Parameters at other levels (`song_analysis()`)

**Characterizing hierarchical levels in acoustic signals**

  - Creating 'song' spectrograms (`full_spectrograms()`, `spectrograms()`)
  - 'Song' parameters (`song_analysis()`)

**Choosing the right method for quantifying structure**  <a href="https://ndownloader.figshare.com/files/27262301" class="btn btn-warning btn-xs" role="button">Compare methods</a>

  - Compare different methods for quantifying structure (`compare_methods()`)

**Quality control in recordings and annotation** <a href="https://ndownloader.figshare.com/files/27263603" class="btn btn-warning btn-xs" role="button">Quality checks</a>

  - Check and modify sound file format (`check_wavs()`, `info_wavs()`, `duration_wavs()`, `mp32wav()` y `fix_wavs()`)
  - Tuning spectrogram parameters (`tweak_spectro()`)
  - Double-checking selection tables (`check_sels()`, `spectrograms()`, `full_spectrograms()` & `catalog()`)
  - Re-adjusting selections (`tailor_sels()`)

&nbsp; 
