<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>modelos_de_regresion.knit</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/clipboard-2.0.6/clipboard.min.js"></script>
<link href="site_libs/xaringanExtra-clipboard-0.2.6/xaringanExtra-clipboard.css" rel="stylesheet" />
<script src="site_libs/xaringanExtra-clipboard-0.2.6/xaringanExtra-clipboard.js"></script>
<script>window.xaringanExtraClipboard(null, {"button":"<i class=\"fa fa-clipboard\"><\/i>","success":"<i class=\"fa fa-check\" style=\"color: #90BE6D\"><\/i>","error":"<i class=\"fa fa-times-circle\" style=\"color: #F94144\"><\/i>"})</script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="extra.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">R avanzado</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Manuales
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="fundamentos_de_r.html">Fundamentos de R</a>
    </li>
    <li>
      <a href="reportes_dinamicos_con_rmarkdown.html">Reportes dinámicos con Rmarkdown</a>
    </li>
    <li>
      <a href="funciones.html">Funciones</a>
    </li>
    <li>
      <a href="bucles_loops.html">Bucles</a>
    </li>
    <li>
      <a href="modelos_de_regresion.html">Modelos de regresión</a>
    </li>
    <li>
      <a href="stadistica_tradicional_en_regresiones.html">Modelos comunes como regresiones</a>
    </li>
    <li>
      <a href="graficos_con_ggplot2.html">Gráficos con ggplot2</a>
    </li>
  </ul>
</li>
<li>
  <a href="preparacion_curso.html">Preparación para el curso</a>
</li>
<li>
  <a href="https://codefile.io/f/XOIzH23KfULuZKyZ1TYT">Compartir código</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Tareas
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="tarea_4.html">Tarea 4</a>
    </li>
    <li>
      <a href="respuestas_tarea_4.html">Solución: tarea 4</a>
    </li>
    <li>
      <a href="tarea_5.html">Tarea 5</a>
    </li>
    <li>
      <a href="respuestas_tarea_5.html">Solución: tarea 5</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://github.com/maRce10/ucr_r_avanzado/raw/master/additional_files/2022-08-05_Probl%20Esp%20Ecol_Estadistica%20Avanzada%20en%20R.pdf">Programa del curso</a>
</li>
<li>
  <a href="instructor.html">Instructor</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore"><center>
<font size="7"><b>Modelos de regresión</b></font>
</center></h1>
<h3 class="subtitle"><center>
<font size="4"><b>Programación y métodos estadísticos avanzados en R</b>
</font>
</center></h3>
<h4 class="author"><center>
<font size="5"><a href="http://marceloarayasalas.weebly.com/">Marcelo
Araya-Salas, PhD</a></font>
</center></h4>
<h4 class="date"><center>
“2022-10-17”
</center></h4>

</div>


<style>
body
  { counter-reset: source-line 0; }
pre.numberSource code
  { counter-reset: none; }
</style>
<p> </p>
<div id="modelos-lineales-como-marco-unificador" class="section level1">
<h1>Modelos lineales como marco unificador</h1>
<p>Tradicionalmente, los modelos estadísticos se han enseñado como
herramientas desconectadas sin una relación clara entre ellas. Sólo hace
falta darle un vistazo a un libro clásico de estadística para biólogos
(Sokal &amp; Rolhf):</p>
<p><img src="images/sokal_rohlf.png" width="100%" style="display: block; margin: auto;" />
 </p>
<p>Sin embargo, la mayoría de esos modelos estadísticos comunes no son
más que casos especiales de modelos lineales. Por lo tanto, aprenderlos
como tales puede simplificar mucho las cosas. Este enfoque tiene varias
ventajas:</p>
<ul>
<li><p>En primer lugar, <strong>todo se reduce a
<em>y=a⋅x+b</em></strong>, lo que simplifica en gran medida el
aprendizaje</p></li>
<li><p>Esto también significa que no hay <strong>necesidad de aprender
sobre los parámetros, las hipótesis y la interpretación de los
resultados para cada caso especial</strong>.</p></li>
<li><p>Los modelos lineales se han ampliado para <strong>tener en cuenta
distribuciones y estructuras de datos complejas</strong> (por ejemplo,
modelos mixtos, modelos lineales generalizados, modelos cero-inflados,
etc.) proporcionando una <strong>plataforma más
flexible</strong>.</p></li>
<li><p>Los modelos lineales se <strong>aplican en todos los paradigmas
estadísticos</strong> (por ejemplo, frecuentista, bayesiano)</p></li>
</ul>
<p> </p>
</div>
<div id="objetivo-del-manual" class="section level1 alert alert-info">
<h1>Objetivo del manual</h1>
<p>  - Comprender la inferencia estadística a través de una única
herramienta de modelaje (modelos lineales en sentido amplio)</p>
<ul>
<li><p>Familiarizarse con la construcción de modelos lineales</p></li>
<li><p>Extender los modelos lineales a diferentes estructuras de
datos</p></li>
</ul>
</div>
<p> </p>
<hr />
<p>Paquetes a utilizar en este manual:</p>
<div class="sourceCode" id="cb1"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># vector con paquetes</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>ptqs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;ggplot2&quot;</span>, <span class="st">&quot;viridis&quot;</span>, <span class="st">&quot;lmerTest&quot;</span>, <span class="st">&quot;sjPlot&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="co"># bucle para instalar/cargar paquetes</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>instalado <span class="ot">&lt;-</span> <span class="fu">sapply</span>(ptqs, <span class="cf">function</span>(y) {</span>
<span id="cb1-6"><a href="#cb1-6"></a></span>
<span id="cb1-7"><a href="#cb1-7"></a>    ptq <span class="ot">&lt;-</span> <span class="fu">strsplit</span>(y, <span class="st">&quot;/&quot;</span>)[[<span class="dv">1</span>]]</span>
<span id="cb1-8"><a href="#cb1-8"></a>    ptq <span class="ot">&lt;-</span> ptq[<span class="fu">length</span>(ptq)]</span>
<span id="cb1-9"><a href="#cb1-9"></a></span>
<span id="cb1-10"><a href="#cb1-10"></a>    <span class="cf">if</span> (<span class="sc">!</span>ptq <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">&quot;Package&quot;</span>]) {</span>
<span id="cb1-11"><a href="#cb1-11"></a>        <span class="cf">if</span> (<span class="fu">grepl</span>(<span class="st">&quot;/&quot;</span>, y))</span>
<span id="cb1-12"><a href="#cb1-12"></a>            remotes<span class="sc">::</span><span class="fu">install_github</span>(y, <span class="at">force =</span> <span class="cn">TRUE</span>) <span class="cf">else</span> <span class="fu">install.packages</span>(y)</span>
<span id="cb1-13"><a href="#cb1-13"></a>    }</span>
<span id="cb1-14"><a href="#cb1-14"></a></span>
<span id="cb1-15"><a href="#cb1-15"></a>    <span class="fu">try</span>(<span class="fu">require</span>(ptq, <span class="at">character.only =</span> <span class="cn">TRUE</span>), <span class="at">silent =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-16"><a href="#cb1-16"></a>})</span></code></pre></div>
<p> </p>
<hr />
<div id="cómo-simular-datos" class="section level1">
<h1>Cómo simular datos</h1>
<div id="generación-de-números-aleatorios-en-r" class="section level2">
<h2>Generación de números aleatorios en R</h2>
<p>La estadística nos permite inferir patrones en los datos. Solemos
utilizar conjuntos de datos reales para enseñar estadística. Sin
embargo, puede ser circular entender el funcionamiento interno de una
herramienta estadística probando su capacidad para inferir un patrón que
no estamos seguros de encontrar en los datos (y no tenemos idea del
mecanismo que produjo ese patrón). <strong>Las simulaciones nos permiten
crear escenarios controlados en los que conocemos con seguridad los
patrones</strong> presentes en los datos y los procesos subyacentes que
los han generado.</p>
<p>R ofrece algunas funciones básicas para la simulación de datos. Las
más utilizadas son las funciones generadoras de números aleatorios. Los
nombres de estas funciones comienzan con <em>r</em>
(<code>r____()</code>). Por ejemplo, <code>runif()</code>:</p>
<div class="sourceCode" id="cb2"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># simular variable uniforme</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>unif_var <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">10</span>)</span></code></pre></div>
<p> </p>
<p>El resultado es un vector numérico de longitud 100
(<code>n = 100</code>):</p>
<div class="sourceCode" id="cb3"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># imprimir variable</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>unif_var</span></code></pre></div>
<pre><code>##   [1] 9.88909298 3.97745453 1.15697779 0.69748679 2.43749391 7.92010426
##   [7] 3.40062353 9.72062501 1.65855485 4.59103666 1.71748077 2.31477102
##  [13] 7.72811946 0.96301542 4.53447770 0.84700713 5.60665867 0.08704600
##  [19] 9.85737091 3.16584804 6.39448942 2.95223235 9.96703694 9.06021320
##  [25] 9.88739144 0.65645739 6.27038758 4.90475041 9.71024413 3.62220848
##  [31] 6.79993461 2.63719930 1.85714261 1.85143222 3.79296747 8.47024392
##  [37] 4.98076133 7.90585574 8.38463872 4.56903865 7.99475815 3.81943061
##  [43] 7.59701231 4.36775602 9.04217721 3.19534914 0.82569093 8.16289079
##  [49] 8.98476221 9.66496398 5.73068883 7.20079497 7.74058624 6.27760801
##  [55] 7.22989341 3.86831279 1.62790778 1.87228283 3.91249474 2.73901210
##  [61] 1.91917748 5.04391806 7.63840357 6.93668871 5.44054188 6.59087226
##  [67] 4.68728380 4.81805539 3.37063598 4.24526302 2.87015131 6.01191532
##  [73] 8.40742326 6.20837048 1.34551619 5.67722430 4.43426331 4.37975423
##  [79] 6.23617233 9.32653342 8.88492583 8.78540561 2.42176948 7.41453797
##  [85] 3.87656313 0.78951739 0.94835550 7.62142731 3.47894026 4.16766709
##  [91] 3.44016231 0.08410923 9.11574991 1.82205419 7.22803449 5.71963331
##  [97] 5.40036414 3.54947415 8.24091838 1.86136761</code></pre>
<p> </p>
<p>Podemos explorar el resultado graficando un histograma:</p>
<div class="sourceCode" id="cb5"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># crear histograma</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(unif_var), <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> unif_var)) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>    <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-7-1.png" width="672" />
 </p>
<p>Muestra una distribución uniforme que va de 0 a 10.</p>
<p>También podemos simular números aleatorios procedentes de una
distribución normal utilizando <code>rnorm()</code>:</p>
<div class="sourceCode" id="cb6"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># crear una variable normal</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>norm_var <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb6-3"><a href="#cb6-3"></a></span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="co"># graficar histograma</span></span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(norm_var), <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> norm_var)) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6"></a>    <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p> </p>
<p>Tenga en cuenta que todas las funciones generadoras de números
aleatorios tienen el argumento ‘n’, que determina la longitud del vector
generado (es decir, el número de números aleatorios), además de algunos
argumentos adicionales relacionados con parámetros específicos de la
distribución.</p>
<p>Las variables continuas (es decir, los vectores numéricos) pueden
convertirse en variables discretas (es decir, números enteros)
simplemente redondeándolas:</p>
<div class="sourceCode" id="cb7"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>v1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">5</span>, <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb7-2"><a href="#cb7-2"></a></span>
<span id="cb7-3"><a href="#cb7-3"></a>v1</span></code></pre></div>
<pre><code>## [1] 15.426886  8.544965 15.138700  8.920290  9.369333</code></pre>
<div class="sourceCode" id="cb9"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">round</span>(<span class="at">x =</span> v1, <span class="at">digits =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 15  9 15  9  9</code></pre>
<p> </p>
<div class="alert alert-info">
<p><font size="5">Ejercicio 1</font></p>
<ul>
<li><p>¿Qué hacen las funciones <code>rbinom()</code> y
<code>rexp()</code>?</p></li>
<li><p>Ejecutela y haga histogramas de sus resultados</p></li>
<li><p>¿Qué hacen los argumentos ‘mean’ y ‘sd’ en <code>rnorm()</code>?
Juege con diferentes valores y comprueba el histograma para hacerse una
idea de su efecto en la simulación</p></li>
</ul>
</div>
<p> </p>
</div>
<div id="generación-de-variables-categóricas" class="section level2">
<h2>Generación de variables categóricas</h2>
<p>La forma más sencilla de generar variables categóricas es utilizar el
vector de ejemplo <code>letters' (o</code>LETTERS’) para asignar niveles
de categoría. Podemos hacerlo utilizando la función <code>rep()</code>.
Por ejemplo, el siguiente código crea un vector categórico (caracteres)
con dos niveles, cada uno con 4 observaciones:</p>
<div class="sourceCode" id="cb11"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">rep</span>(letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">each =</span> <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] &quot;a&quot; &quot;a&quot; &quot;a&quot; &quot;a&quot; &quot;b&quot; &quot;b&quot; &quot;b&quot; &quot;b&quot;</code></pre>
<p> </p>
<p>También podemos replicar este patrón utilizando el argumento ‘times’.
Este código replica el vector anterior 2 veces:</p>
<div class="sourceCode" id="cb13"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">rep</span>(letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">each =</span> <span class="dv">4</span>, <span class="at">times =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;a&quot; &quot;a&quot; &quot;a&quot; &quot;a&quot; &quot;b&quot; &quot;b&quot; &quot;b&quot; &quot;b&quot; &quot;a&quot; &quot;a&quot; &quot;a&quot; &quot;a&quot; &quot;b&quot; &quot;b&quot; &quot;b&quot; &quot;b&quot;</code></pre>
<p> </p>
<p>Otra opción es simular una variable a partir de una distribución
binomial y luego convertirla en un factor:</p>
<div class="sourceCode" id="cb15"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># correr rbinom</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>binom_var <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">50</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span>
<span id="cb15-3"><a href="#cb15-3"></a></span>
<span id="cb15-4"><a href="#cb15-4"></a>binom_var</span></code></pre></div>
<pre><code>##  [1] 1 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0
## [39] 1 1 0 0 0 0 0 1 0 1 1 1</code></pre>
<div class="sourceCode" id="cb17"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># convertir a factor</span></span>
<span id="cb17-2"><a href="#cb17-2"></a>categ_var <span class="ot">&lt;-</span> <span class="fu">factor</span>(binom_var, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>))</span>
<span id="cb17-3"><a href="#cb17-3"></a></span>
<span id="cb17-4"><a href="#cb17-4"></a>categ_var</span></code></pre></div>
<pre><code>##  [1] b a a b b a a a a a a a b b b a a b a b a a a a a a a b a b b b a a a b a a
## [39] b b a a a a a b a b b b
## Levels: a b</code></pre>
<p> </p>
</div>
<div id="muestreo-aleatorio" class="section level2">
<h2>Muestreo aleatorio</h2>
<p>La otra herramienta importante de R para jugar con datos simulados es
<code>sample()</code>. Esta función permite tomar muestras de tamaños
específicos de vectores. Por ejemplo, tomemos el ejemplo del vector
‘letters’:</p>
<div class="sourceCode" id="cb19"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>letters</span></code></pre></div>
<pre><code>##  [1] &quot;a&quot; &quot;b&quot; &quot;c&quot; &quot;d&quot; &quot;e&quot; &quot;f&quot; &quot;g&quot; &quot;h&quot; &quot;i&quot; &quot;j&quot; &quot;k&quot; &quot;l&quot; &quot;m&quot; &quot;n&quot; &quot;o&quot; &quot;p&quot; &quot;q&quot; &quot;r&quot; &quot;s&quot;
## [20] &quot;t&quot; &quot;u&quot; &quot;v&quot; &quot;w&quot; &quot;x&quot; &quot;y&quot; &quot;z&quot;</code></pre>
<p> </p>
<p>Podemos tomar una muestra de este vector como es:</p>
<div class="sourceCode" id="cb21"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="co"># tomar muestra</span></span>
<span id="cb21-2"><a href="#cb21-2"></a><span class="fu">sample</span>(<span class="at">x =</span> letters, <span class="at">size =</span> <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;i&quot; &quot;r&quot; &quot;q&quot; &quot;a&quot; &quot;c&quot; &quot;m&quot; &quot;y&quot; &quot;z&quot; &quot;u&quot; &quot;v&quot;</code></pre>
<p> </p>
<p>El argumento ‘size’ nos permite determinar el tamaño de la muestra.
Tenga en cuenta que obtendremos un error si el tamaño es mayor que el
propio vector:</p>
<div class="sourceCode" id="cb23"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">sample</span>(<span class="at">x =</span> letters, <span class="at">size =</span> <span class="dv">30</span>)</span></code></pre></div>
<pre><code>## Error in sample.int(length(x), size, replace, prob): cannot take a sample larger than the population when &#39;replace = FALSE&#39;</code></pre>
<p> </p>
<p>Esto sólo puede hacerse cuando el muestreo es con reemplazo
(replacement). El muestreo con reemplazo puede aplicarse estableciendo
el argumento <code>replace = TRUE</code>:</p>
<div class="sourceCode" id="cb25"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="fu">sample</span>(<span class="at">x =</span> letters, <span class="at">size =</span> <span class="dv">30</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;j&quot; &quot;i&quot; &quot;h&quot; &quot;i&quot; &quot;k&quot; &quot;u&quot; &quot;n&quot; &quot;i&quot; &quot;w&quot; &quot;k&quot; &quot;c&quot; &quot;t&quot; &quot;m&quot; &quot;p&quot; &quot;i&quot; &quot;h&quot; &quot;d&quot; &quot;w&quot; &quot;c&quot;
## [20] &quot;q&quot; &quot;j&quot; &quot;e&quot; &quot;e&quot; &quot;j&quot; &quot;k&quot; &quot;c&quot; &quot;l&quot; &quot;t&quot; &quot;r&quot; &quot;h&quot;</code></pre>
<p> </p>
</div>
<div id="iterar-un-proceso" class="section level2">
<h2>Iterar un proceso</h2>
<p>A menudo, las simulaciones deben repetirse varias veces para
descartar resultados espurios debidos al azar o simplemente para probar
diferentes parámetros. Las funciones de simulación de datos mencionadas
anteriormente pueden ejecutarse varias veces (por ejemplo, iteradas)
utilizando la función <code>replicate()</code>:</p>
<div class="sourceCode" id="cb27"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co"># replicar</span></span>
<span id="cb27-2"><a href="#cb27-2"></a>repl_rnorm <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="at">n =</span> <span class="dv">3</span>, <span class="at">expr =</span> <span class="fu">rnorm</span>(<span class="dv">2</span>), <span class="at">simplify =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-3"><a href="#cb27-3"></a></span>
<span id="cb27-4"><a href="#cb27-4"></a><span class="co"># ver clase</span></span>
<span id="cb27-5"><a href="#cb27-5"></a><span class="fu">class</span>(repl_rnorm)</span></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<div class="sourceCode" id="cb29"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># imprimir</span></span>
<span id="cb29-2"><a href="#cb29-2"></a>repl_rnorm</span></code></pre></div>
<pre><code>## [[1]]
## [1]  1.1918356 -0.3399238
## 
## [[2]]
## [1]  0.7891082 -0.6321324
## 
## [[3]]
## [1] -1.4931226 -0.1344123</code></pre>
<p> </p>
</div>
<div id="hacer-que-las-simulaciones-sean-reproducibles"
class="section level2">
<h2>Hacer que las simulaciones sean reproducibles</h2>
<p>El último truco que necesitamos para ejecutar simulaciones en R es la
capacidad de reproducir una simulación (es decir, obtener exactamente
los mismos datos y resultados simulados). Esto puede ser útil para que
otros investigadores puedan ejecutar nuestros análisis exactamente de la
misma manera. Esto puede hacerse fácilmente con la función
<code>set.seed()</code>. Pruebe a ejecutar el siguiente código. Debería
obtener la misma salida:</p>
<div class="sourceCode" id="cb31"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># definir semilla</span></span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="fu">set.seed</span>(<span class="dv">10</span>)</span>
<span id="cb31-3"><a href="#cb31-3"></a></span>
<span id="cb31-4"><a href="#cb31-4"></a><span class="co"># crear variable uniforme</span></span>
<span id="cb31-5"><a href="#cb31-5"></a><span class="fu">runif</span>(<span class="at">n =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.5074782 0.3067685</code></pre>
<hr />
</div>
</div>
<div id="crear-juegos-de-datos" class="section level1">
<h1>Crear juegos de datos</h1>
<div id="juegos-de-datos-con-variables-numéricas-y-categóricas"
class="section level2">
<h2>Juegos de datos con variables numéricas y categóricas</h2>
<p>Ahora que sabemos cómo simular variables continuas y categóricas.
Podemos juntarlas para crear conjuntos de datos simulados. Esto se puede
hacer utilizando la función <code>data.frame()</code>:</p>
<div class="sourceCode" id="cb33"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># crear variable categorica</span></span>
<span id="cb33-2"><a href="#cb33-2"></a>grupo <span class="ot">&lt;-</span> <span class="fu">rep</span>(letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">each =</span> <span class="dv">3</span>)</span>
<span id="cb33-3"><a href="#cb33-3"></a></span>
<span id="cb33-4"><a href="#cb33-4"></a><span class="co"># crear variable continuaa</span></span>
<span id="cb33-5"><a href="#cb33-5"></a>size <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">6</span>, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb33-6"><a href="#cb33-6"></a></span>
<span id="cb33-7"><a href="#cb33-7"></a><span class="co"># poner juntas en un data frame</span></span>
<span id="cb33-8"><a href="#cb33-8"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(grupo, size)</span>
<span id="cb33-9"><a href="#cb33-9"></a></span>
<span id="cb33-10"><a href="#cb33-10"></a><span class="co"># imprimir</span></span>
<span id="cb33-11"><a href="#cb33-11"></a>df</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
grupo
</th>
<th style="text-align:center;">
size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
4.8157
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
3.6287
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
4.4008
</td>
</tr>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
5.2945
</td>
</tr>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
5.3898
</td>
</tr>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
3.7919
</td>
</tr>
</tbody>
</table>
<p>Por supuesto, podríamos añadir más variables a este cuadro de
datos:</p>
<div class="sourceCode" id="cb34"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="co"># crear variable categorica</span></span>
<span id="cb34-2"><a href="#cb34-2"></a>grupo <span class="ot">&lt;-</span> <span class="fu">rep</span>(letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">each =</span> <span class="dv">3</span>)</span>
<span id="cb34-3"><a href="#cb34-3"></a>individuo <span class="ot">&lt;-</span> <span class="fu">rep</span>(LETTERS[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>])</span>
<span id="cb34-4"><a href="#cb34-4"></a></span>
<span id="cb34-5"><a href="#cb34-5"></a><span class="co"># crear variables continuas</span></span>
<span id="cb34-6"><a href="#cb34-6"></a>size <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">6</span>, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb34-7"><a href="#cb34-7"></a>weight <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">6</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb34-8"><a href="#cb34-8"></a></span>
<span id="cb34-9"><a href="#cb34-9"></a><span class="co"># poner todo en un data frame</span></span>
<span id="cb34-10"><a href="#cb34-10"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(grupo, individuo, size, weight)</span>
<span id="cb34-11"><a href="#cb34-11"></a></span>
<span id="cb34-12"><a href="#cb34-12"></a><span class="co"># imprimir</span></span>
<span id="cb34-13"><a href="#cb34-13"></a>df</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
grupo
</th>
<th style="text-align:center;">
individuo
</th>
<th style="text-align:center;">
size
</th>
<th style="text-align:center;">
weight
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
A
</td>
<td style="text-align:center;">
4.6363
</td>
<td style="text-align:center;">
109.8744
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
B
</td>
<td style="text-align:center;">
3.3733
</td>
<td style="text-align:center;">
107.4139
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
C
</td>
<td style="text-align:center;">
4.7435
</td>
<td style="text-align:center;">
100.8935
</td>
</tr>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
D
</td>
<td style="text-align:center;">
6.1018
</td>
<td style="text-align:center;">
90.4506
</td>
</tr>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
E
</td>
<td style="text-align:center;">
5.7558
</td>
<td style="text-align:center;">
98.0485
</td>
</tr>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
4.7618
</td>
<td style="text-align:center;">
109.2552
</td>
</tr>
</tbody>
</table>
<p>Y eso es un juego de datos simulados en su forma más básica. Se
parece mucho al tipo de datos con los que trabajamos en biología.</p>
<hr />
</div>
</div>
<div
id="cómo-utilizar-datos-simulados-para-entender-el-comportamiento-de-las-herramientas-estadísticas"
class="section level1">
<h1>Cómo utilizar datos simulados para entender el comportamiento de las
herramientas estadísticas</h1>
<p> </p>
<div id="prueba-de-concepto-el-teorema-central-del-límite"
class="section level2">
<h2>Prueba de concepto: <em>el Teorema Central del Límite</em></h2>
<p>El <a
href="https://en.wikipedia.org/wiki/Central_limit_theorem">Teorema del
Límite Central</a> afirma que, si tomamos muestras aleatorias de una
población, los promedios de esas muestras se ajustarán a una
distribución normal, aunque la población no esté distribuida
normalmente. Además, la distribución normal resultante debe tener un
promedio cercanp al promedio de la población. El teorema es un concepto
clave para la estadística inferencial, ya que implica que los métodos
estadísticos que funcionan para las distribuciones normales pueden ser
aplicables a muchos problemas que implican otros tipos de
distribuciones. No obstante, el objetivo aquí es sólo mostrar cómo se
pueden utilizar las simulaciones para entender el comportamiento de los
métodos estadísticos.</p>
<p>Para comprobar si esas afirmaciones básicas sobre el Teorema del
Límite Central son ciertas, podemos utilizar datos simulados en R. Vamos
a simular una población de 1000 observaciones con una distribución
uniforme:</p>
<div class="sourceCode" id="cb35"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="co"># simular popublacion uniforme</span></span>
<span id="cb35-2"><a href="#cb35-2"></a>unif_pop <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1000</span>, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">10</span>)</span>
<span id="cb35-3"><a href="#cb35-3"></a></span>
<span id="cb35-4"><a href="#cb35-4"></a><span class="co"># ver histograma</span></span>
<span id="cb35-5"><a href="#cb35-5"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(unif_pop), <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> unif_pop)) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6"></a>    <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p> </p>
<p>Podemos tomar muestras aleatorias usando <code>sample()</code>
así:</p>
<div class="sourceCode" id="cb36"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="fu">sample</span>(<span class="at">x =</span> unif_pop, <span class="at">size =</span> <span class="dv">30</span>)</span></code></pre></div>
<pre><code>##  [1] 9.2841984 1.0262565 2.5751741 3.3248460 6.8998985 2.2940436 0.3373657
##  [8] 8.2136568 3.3036362 8.0379320 2.5917392 7.8177006 5.6542576 0.6383126
## [15] 2.8347032 4.2043442 4.7632983 4.4219338 6.9782974 7.9262477 0.6812050
## [22] 3.5232307 6.5110308 5.3828892 7.9721010 1.8006177 4.2128214 3.3386579
## [29] 8.9122284 4.7116278</code></pre>
<p> </p>
<p>Este proceso puede ser replicado varias veces con
<code>replicate()</code>:</p>
<div class="sourceCode" id="cb38"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="co"># replicar</span></span>
<span id="cb38-2"><a href="#cb38-2"></a>samples <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">expr =</span> <span class="fu">mean</span>(<span class="fu">sample</span>(<span class="at">x =</span> unif_pop, <span class="at">size =</span> <span class="dv">30</span>)))</span></code></pre></div>
<p> </p>
<p>El código anterior toma 100 muestras con 30 valores cada una. Ahora
podemos comprobar la distribución de las muestras:</p>
<div class="sourceCode" id="cb39"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="co"># ver distribucion/ histograma</span></span>
<span id="cb39-2"><a href="#cb39-2"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(samples), <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> samples)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-27-1.png" width="672" />
 </p>
<p>… asi como el promedio:</p>
<div class="sourceCode" id="cb40"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="fu">mean</span>(samples)</span></code></pre></div>
<pre><code>## [1] 5.021219</code></pre>
<p> </p>
<p>Como era de esperar, las muestras siguen una distribución normal con
una media cercana a la media de la población, que es:</p>
<div class="sourceCode" id="cb42"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="fu">mean</span>(unif_pop)</span></code></pre></div>
<pre><code>## [1] 5.052715</code></pre>
<p> </p>
<p>Probemos con una distribución más compleja. Por ejemplo, una
distribución bimodal:</p>
<div class="sourceCode" id="cb44"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="co"># usar semilla</span></span>
<span id="cb44-2"><a href="#cb44-2"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb44-3"><a href="#cb44-3"></a></span>
<span id="cb44-4"><a href="#cb44-4"></a><span class="co"># simular variables</span></span>
<span id="cb44-5"><a href="#cb44-5"></a>norm1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb44-6"><a href="#cb44-6"></a>norm2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">20</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb44-7"><a href="#cb44-7"></a></span>
<span id="cb44-8"><a href="#cb44-8"></a><span class="co"># juntar en una sola variable</span></span>
<span id="cb44-9"><a href="#cb44-9"></a>bimod_pop <span class="ot">&lt;-</span> <span class="fu">c</span>(norm1, norm2)</span>
<span id="cb44-10"><a href="#cb44-10"></a></span>
<span id="cb44-11"><a href="#cb44-11"></a><span class="co"># ver histograma</span></span>
<span id="cb44-12"><a href="#cb44-12"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(bimod_pop), <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> bimod_pop)) <span class="sc">+</span></span>
<span id="cb44-13"><a href="#cb44-13"></a>    <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<div class="sourceCode" id="cb45"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="co"># replicar muestreo</span></span>
<span id="cb45-2"><a href="#cb45-2"></a>samples <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">200</span>, <span class="fu">mean</span>(<span class="fu">sample</span>(bimod_pop, <span class="dv">10</span>)))</span>
<span id="cb45-3"><a href="#cb45-3"></a></span>
<span id="cb45-4"><a href="#cb45-4"></a><span class="co"># ver histograma</span></span>
<span id="cb45-5"><a href="#cb45-5"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(samples), <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> samples)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<div class="sourceCode" id="cb46"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="co"># ver promedios</span></span>
<span id="cb46-2"><a href="#cb46-2"></a><span class="fu">mean</span>(samples)</span></code></pre></div>
<pre><code>## [1] 15.23058</code></pre>
<div class="sourceCode" id="cb48"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="fu">mean</span>(bimod_pop)</span></code></pre></div>
<pre><code>## [1] 15.08789</code></pre>
<p> </p>
<div class="alert alert-info">
<p><font size="5">Ejercicio 2</font></p>
<p> </p>
<ul>
<li><p>Intenta explorar el Teorema del Límite Central como en el caso
anterior, pero esta vez utilizando:</p>
<ol style="list-style-type: decimal">
<li>Una distribución exponencial (<code>rexp()</code>)</li>
<li>Una distribución binomial (<code>rbinom()</code>)</li>
</ol></li>
</ul>
<p> </p>
<ul>
<li>Para cada distribución: grafique un histograma y compare los
promedios de la población y de las muestras</li>
</ul>
</div>
<p> </p>
<hr />
<div class="alert alert-warning">
<font size = 6>
<center>
Regresión lineal simple
</center>
<p></font></p>
<p>Las regresiones lineales se basan en la ecuación lineal <em>a = mx +
b</em> que aprendimos en el colegio. La representación formal tiene este
aspecto:</p>
<center>
<font size = 6><span class="math inline">\(\hat{Y} \sim \beta_{o} +
\beta_{1} * x_{1}\)</span></font>
</center>
<p> </p>
<ul>
<li><p><span class="math inline">\(\hat{Y}\)</span>: variable
respuesta</p></li>
<li><p><span class="math inline">\(\beta_{o}\)</span>:
intercepto</p></li>
<li><p><span class="math inline">\(\beta_{1}\)</span>: estimado de la
magnitud del efecto de <span class="math inline">\(x_{1}\)</span> en
<span class="math inline">\(\hat{Y}\)</span> (también conocido como
tamaño de efecto, coeficiente o simplemente “estimado”)</p></li>
<li><p><span class="math inline">\(x_{1}\)</span>: variable
predictora</p></li>
</ul>
<p> </p>
<p>El objetivo más común de una regresión lineal es la estimación de los
valores de <span class="math inline">\(\beta_{*}\)</span>. Esto se
consigue encontrando la línea recta que mejor se ajusta y que representa
la asociación entre un predictor y la respuesta:</p>
<p><img src="images/regression.jpg" width="100%" style="display: block; margin: auto;" />
 </p>
<p>Estos <span class="math inline">\(\beta_{*}\)</span> son el tamaño de
efecto estimado del predictor correspondiente (por ejemplo, <span
class="math inline">\(\beta_{1}\)</span> es el tamaño de efecto <span
class="math inline">\(x_{1}\)</span>). Su valor representa el cambio
medio en <span class="math inline">\(\hat{Y}\)</span> (en unidades <span
class="math inline">\(\hat{Y}\)</span>) para una unidad de cambio en
<span class="math inline">\(\beta_{*}\)</span>. Por lo tanto, la
hipótesis nula es que esos <span
class="math inline">\(\beta_{*}\)</span> no son diferentes de 0:</p>
<center>
<font size = 6><span class="math inline">\(\qquad \mathcal{H}_0: \hat{Y}
= \beta_0 + 0 * x_{1}\)</span></font>
</center>
<p>lo que equivale a esto:</p>
<center>
<font size = 6><span class="math inline">\(\qquad \mathcal{H}_0: \hat{Y}
= \beta_0\)</span></font>
</center>
<p> </p>
<p>Por ejemplo, un modelo de regresión con este resultado:</p>
<p><img src="images/model_betas_esp.png" width="90%" style="display: block; margin: auto;" /></p>
<p> </p>
</div>
<p> </p>
<hr />
</div>
</div>
<div id="regresión-lineal-en-r" class="section level1">
<h1>Regresión lineal en R</h1>
<p>Para sacar el máximo provecho de los modelos lineales necesitamos
sentirnos cómodos con ellos. Empezaremos explorando la función de
regresión lineal de R <code>lm()</code>. En R la mayoría de los modelos
lineales y sus extensiones comparten formatos comunes de entrada de
datos y resultados, lo que facilita su aplicación una vez que entendemos
sus fundamentos.</p>
<p>Utilizaremos el juego de datos ‘trees’ que viene por defecto con R.
‘trees’ proporciona medidas del <strong>diámetro</strong> (etiquetado
como ‘Girth’), <strong>altura</strong> y <strong>volumen</strong> de 31
cerezos talados:</p>
<div class="sourceCode" id="cb50"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="fu">head</span>(trees)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Girth
</th>
<th style="text-align:center;">
Height
</th>
<th style="text-align:center;">
Volume
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
8.3
</td>
<td style="text-align:center;">
70
</td>
<td style="text-align:center;">
10.3
</td>
</tr>
<tr>
<td style="text-align:center;">
8.6
</td>
<td style="text-align:center;">
65
</td>
<td style="text-align:center;">
10.3
</td>
</tr>
<tr>
<td style="text-align:center;">
8.8
</td>
<td style="text-align:center;">
63
</td>
<td style="text-align:center;">
10.2
</td>
</tr>
<tr>
<td style="text-align:center;">
10.5
</td>
<td style="text-align:center;">
72
</td>
<td style="text-align:center;">
16.4
</td>
</tr>
<tr>
<td style="text-align:center;">
10.7
</td>
<td style="text-align:center;">
81
</td>
<td style="text-align:center;">
18.8
</td>
</tr>
<tr>
<td style="text-align:center;">
10.8
</td>
<td style="text-align:center;">
83
</td>
<td style="text-align:center;">
19.7
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>La función básica de R para construir un modelo lineal es
<code>lm()</code>. Veamos los componentes básicos de un modelo de
regresión utilizando <code>lm()</code>:</p>
<p><img src="images/lm.png" width="100%" style="display: block; margin: auto;" />
 </p>
<p>Podemos ajustar este modelo para ver el resultado:</p>
<div class="sourceCode" id="cb51"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a>reg_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Height <span class="sc">~</span> Girth, <span class="at">data =</span> trees)</span>
<span id="cb51-2"><a href="#cb51-2"></a></span>
<span id="cb51-3"><a href="#cb51-3"></a><span class="fu">summary</span>(reg_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Height ~ Girth, data = trees)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -12.5816  -2.7686   0.3163   2.4728   9.9456 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  62.0313     4.3833  14.152 1.49e-14 ***
## Girth         1.0544     0.3222   3.272  0.00276 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.538 on 29 degrees of freedom
## Multiple R-squared:  0.2697, Adjusted R-squared:  0.2445 
## F-statistic: 10.71 on 1 and 29 DF,  p-value: 0.002758</code></pre>
<p> </p>
<p>Esto es lo que significan los elementos de la salida:</p>
<ul>
<li><p><strong>Llamada</strong> (call): la función y los parámetros que
se utilizaron para crear el modelo</p></li>
<li><p><strong>Residuales</strong> (residuals): distribución de los
residuales. Los residuales son la diferencia entre lo que predijo el
modelo y el valor real de <em>y</em>. Esta es una representación gráfica
de los residuales:</p></li>
</ul>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-41-1.png" width="672" />
 </p>
<ul>
<li><p><strong>Coeficientes</strong> (coefficients): contiene los
tamaños de efecto (‘Estimates’), una medida de su incertidumbre
(‘Standar error’), la estadística asociada (‘t value’) y el valor p
(‘Pr(&gt;|t|)’). Los tamaño de efecto o estimados se dan como el cambio
promedio en <em>y</em> por cada aumento de 1 unidad en <em>x</em>. Para
este ejemplo el estimado es de 1,0544 <span class="math inline">\(in /
in\)</span>. A pesar de que las unidades se anulan (`1,0544 <span
class="math inline">\(in / in\)</span> = 1,0544) tenerlas en cuenta
sigue siendo biológicamente significativo. Significan que, en promedio,
y un aumento de 1 pulgada en la circunferencia que se espera un aumento
de 1,0544 pulgadas en la altura.</p></li>
<li><p><strong>Error estándar de los residuales</strong> (residual
standard error): se explica por sí mismo. El error estándar de los
residuales</p></li>
<li><p><strong>R-cuadrado múltiple</strong> (multiple R-squared): el
coeficiente de determinación, que pretende ser una medida de lo bien que
su modelo se ajusta a los datos</p></li>
<li><p><strong>R-cuadrado ajustado</strong> (adjusted R-squared):
similar al ‘R-cuadrado múltiple’ pero penalizado por el número de
parámetros</p></li>
<li><p><strong>Estadístico F</strong> (F-statistic): estadístico para
una prueba global que comprueba si al menos uno de sus coeficientes es
distinto de cero</p></li>
<li><p><strong>Valor de p</strong>: probabilidad de una prueba global
que comprueba si al menos uno de sus coeficientes es distinto de
cero</p></li>
</ul>
<p> </p>
<p>Utilizaremos <code>lm()</code> para mostrar la flexibilidad de los
modelos de regresión. Los componentes de regresión se añadirán
gradualmente para que podamos tomarnos el tiempo de entender cada uno de
ellos así como los correspondientes cambios en la salida de la
regresión.</p>
<hr />
<div id="modelo-solo-con-intercepto" class="section level2">
<h2>Modelo solo con intercepto</h2>
<p>Primero vamos a crear una variable numérica de respuesta:</p>
<div class="sourceCode" id="cb53"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a><span class="co"># definir semilla</span></span>
<span id="cb53-2"><a href="#cb53-2"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb53-3"><a href="#cb53-3"></a></span>
<span id="cb53-4"><a href="#cb53-4"></a><span class="co"># numero de observaciones</span></span>
<span id="cb53-5"><a href="#cb53-5"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb53-6"><a href="#cb53-6"></a></span>
<span id="cb53-7"><a href="#cb53-7"></a><span class="co"># variables aleatorias</span></span>
<span id="cb53-8"><a href="#cb53-8"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb53-9"><a href="#cb53-9"></a></span>
<span id="cb53-10"><a href="#cb53-10"></a><span class="co"># put it in a data frame</span></span>
<span id="cb53-11"><a href="#cb53-11"></a>y_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(y)</span></code></pre></div>
<p> </p>
<p>Esta única variable puede introducirse en un <strong>modelo de
regresión sólo con intercepto</strong>. Para ello, debemos suministrar
la fórmula del modelo y los datos a <code>lm()</code>:</p>
<div class="sourceCode" id="cb54"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="co"># run model</span></span>
<span id="cb54-2"><a href="#cb54-2"></a>y_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> y_data)</span></code></pre></div>
<p> </p>
<p>Lo que equivale a:</p>
<center>
<font size = 6><span class="math inline">\(\hat{Y} \sim
\beta_{o}\)</span></font>
</center>
<p> </p>
<p>Podemos obtener el resumen por defecto de los resultados del modelo
ejecutando <code>summary()</code> en el objeto de salida ‘y_mod’:</p>
<div class="sourceCode" id="cb55"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1"></a><span class="fu">summary</span>(y_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ 1, data = y_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.0010 -0.5937 -0.1070  0.6638  2.1345 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)   0.0344     0.1309   0.263    0.794
## 
## Residual standard error: 0.9259 on 49 degrees of freedom</code></pre>
<p> </p>
<p>Puede ser bastante informativo graficar los tamaños de efecto (aunque
en este caso sólo tenemos uno):</p>
<div class="sourceCode" id="cb57"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a>ci_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">param =</span> <span class="fu">names</span>(y_mod<span class="sc">$</span>coefficients), <span class="at">est =</span> y_mod<span class="sc">$</span>coefficients,</span>
<span id="cb57-2"><a href="#cb57-2"></a>    <span class="fu">confint</span>(y_mod))</span>
<span id="cb57-3"><a href="#cb57-3"></a></span>
<span id="cb57-4"><a href="#cb57-4"></a><span class="fu">ggplot</span>(ci_df, <span class="fu">aes</span>(<span class="at">x =</span> param, <span class="at">y =</span> est)) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>,</span>
<span id="cb57-5"><a href="#cb57-5"></a>    <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> X2.<span class="dv">5</span>.., <span class="at">ymax =</span> X97.<span class="dv">5</span>..)) <span class="sc">+</span></span>
<span id="cb57-6"><a href="#cb57-6"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Parámetro&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tamaño de efecto&quot;</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-45-1.png" width="672" />
 </p>
<div class="alert alert-success">
<p> </p>
<center>
<font size="5"><b>Interpretación del modelo</b></font>
</center>
<p> </p>
<p>Para evaluar la importancia de la asociación nos centramos en la
tabla de coeficientes:</p>
<pre><code>##               Estimate Std. Error   t value Pr(&gt;|t|)
## (Intercept) 0.03440355  0.1309378 0.2627473 0.793847</code></pre>
<ul>
<li><p>En este ejemplo no hay predictores en el modelo, por lo que sólo
tenemos una estimación para el intercepto (<span
class="math inline">\(\beta_0\)</span>)</p></li>
<li><p>El modelo nos dice que el intercepto se estima en 0.0344035 y que
este valor no es significativamente diferente de 0 (valor p =
0.793847)</p></li>
<li><p>En este caso el intercepto es simplemente la media de la variable
de respuesta</p></li>
</ul>
<div class="sourceCode" id="cb59"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a><span class="fu">mean</span>(y_data<span class="sc">$</span>y)</span></code></pre></div>
<pre><code>## [1] 0.03440355</code></pre>
<p> </p>
<ul>
<li>Rara vez tenemos predicciones sobre el intercepto, por lo que
tendemos a ignorar esta estimación.</li>
</ul>
</div>
<p> </p>
<div class="alert alert-warning">
<center>
<font size="5"><b>Caso de estudio</b></font>
</center>
<p> </p>
<ul>
<li>Ruhs, E. C., Martin, L. B., &amp; Downs, C. J. (2020). <a
href="https://royalsocietypublishing.org/doi/pdf/10.1098/rspb.2020.0655?download=true"><strong>The
impacts of body mass on immune cell concentrations in
birds</strong></a>. <em>Proceedings of the Royal Society B</em>,
287(1934), 20200655.</li>
</ul>
<p>“<em>Encontramos que un modelo sólo con intercepto (intercept-only
model) explicaba mejor las concentraciones de linfocitos y eosinófilos
en las aves, indicando que las concentraciones de estos tipos de células
eran independientes de la masa corporal.</em>”</p>
<p><img src="images/leukocytes.png" width="85%" style="display: block; margin: auto;" />
 </p>
</div>
<p> </p>
<div class="alert alert-info">
<p><font size="5">Ejercicio 3</font></p>
<p> </p>
<ul>
<li><p>Cambie el argumento ‘mean’ en la llamada de la función “rnorm()`
(<a href="#cb53-8">línea 130</a>) por un valor distinto de 0 y observe
cómo cambian los valores en la tabla de coeficientes</p></li>
<li><p>Cambia el argumento <code>sd</code> en la llamada a la función
<code>rnorm()</code> (<a href="#cb53-8">línea 130</a>) por un valor más
alto y observe cómo cambian los valores en la tabla de
coeficientes</p></li>
</ul>
</div>
<p> </p>
<hr />
</div>
<div id="añadir-un-predictor-no-asociado" class="section level2">
<h2>Añadir un predictor no asociado</h2>
<p>Podemos crear 2 variables numéricas no relacionadas así:</p>
<div class="sourceCode" id="cb61"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a><span class="co"># definir semilla</span></span>
<span id="cb61-2"><a href="#cb61-2"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb61-3"><a href="#cb61-3"></a></span>
<span id="cb61-4"><a href="#cb61-4"></a><span class="co"># numero de observaciones</span></span>
<span id="cb61-5"><a href="#cb61-5"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb61-6"><a href="#cb61-6"></a></span>
<span id="cb61-7"><a href="#cb61-7"></a><span class="co"># variables aleatorias</span></span>
<span id="cb61-8"><a href="#cb61-8"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb61-9"><a href="#cb61-9"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb61-10"><a href="#cb61-10"></a></span>
<span id="cb61-11"><a href="#cb61-11"></a><span class="co"># crear data frame</span></span>
<span id="cb61-12"><a href="#cb61-12"></a>xy_datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x1, y)</span></code></pre></div>
<p> </p>
<p>Estas dos variables pueden introducirse en un modelo de regresión
para evaluar la asociación entre ellas:</p>
<div class="sourceCode" id="cb62"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a><span class="co"># construir model</span></span>
<span id="cb62-2"><a href="#cb62-2"></a>xy_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1, <span class="at">data =</span> xy_datos)</span>
<span id="cb62-3"><a href="#cb62-3"></a></span>
<span id="cb62-4"><a href="#cb62-4"></a><span class="co"># graficar</span></span>
<span id="cb62-5"><a href="#cb62-5"></a><span class="fu">ggplot</span>(xy_datos, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y)) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb62-6"><a href="#cb62-6"></a>    <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">geom_point</span>()  <span class="co"># plot points</span></span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-50-1.png" width="672" />
 </p>
<p>Que es equivalente a esto:</p>
<center>
<font size = 6><span class="math inline">\(\hat{Y} \sim \beta_{o} +
\beta_{1} * x_{1}\)</span></font>
</center>
<p> </p>
<p>Imprimamos el resumen de este modelo:</p>
<div class="sourceCode" id="cb63"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1"></a><span class="fu">summary</span>(xy_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1, data = xy_datos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.0044 -0.6239 -0.1233  0.6868  2.1061 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  0.03977    0.13396   0.297    0.768
## x1          -0.03668    0.14750  -0.249    0.805
## 
## Residual standard error: 0.9349 on 48 degrees of freedom
## Multiple R-squared:  0.001287,   Adjusted R-squared:  -0.01952 
## F-statistic: 0.06184 on 1 and 48 DF,  p-value: 0.8047</code></pre>
<p> </p>
<p>… y graficar los tamaños de efecto:</p>
<div class="sourceCode" id="cb65"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1"></a>ci_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">param =</span> <span class="fu">names</span>(xy_mod<span class="sc">$</span>coefficients), <span class="at">est =</span> xy_mod<span class="sc">$</span>coefficients,</span>
<span id="cb65-2"><a href="#cb65-2"></a>    <span class="fu">confint</span>(xy_mod))</span>
<span id="cb65-3"><a href="#cb65-3"></a></span>
<span id="cb65-4"><a href="#cb65-4"></a><span class="fu">ggplot</span>(ci_df, <span class="fu">aes</span>(<span class="at">x =</span> param, <span class="at">y =</span> est)) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>,</span>
<span id="cb65-5"><a href="#cb65-5"></a>    <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> X2.<span class="dv">5</span>.., <span class="at">ymax =</span> X97.<span class="dv">5</span>..)) <span class="sc">+</span></span>
<span id="cb65-6"><a href="#cb65-6"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Parámetro&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tamaño de efecto&quot;</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-52-1.png" width="672" />
 </p>
<p>Deberíamos “diagnosticar” la idoneidad del modelo inspeccionando más
de cerca la distribución de los residuales. La función
<code>plot_model()</code> del paquete <code>sjPlot</code> hace un buen
trabajo para crear gráficos de diagnóstico para modelos lineales:</p>
<div class="sourceCode" id="cb66"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a><span class="fu">plot_model</span>(xy_mod, <span class="at">type =</span> <span class="st">&quot;diag&quot;</span>)</span></code></pre></div>
<pre><code>## [[1]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-53-1.png" width="80%" /></p>
<pre><code>## 
## [[2]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-53-2.png" width="80%" /></p>
<pre><code>## 
## [[3]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-53-3.png" width="80%" />
 </p>
<div class="alert alert-success">
<p> </p>
<center>
<font size="5"><b>Interpretación del modelo</b></font>
</center>
<p> </p>
<p>Cuadro con coeficientes:</p>
<pre><code>##                Estimate Std. Error    t value  Pr(&gt;|t|)
## (Intercept)  0.03977364  0.1339616  0.2969033 0.7678214
## x1          -0.03667889  0.1474982 -0.2486735 0.8046743</code></pre>
<p> </p>
<ul>
<li><p>En este ejemplo hemos añadido un predictor al modelo, por lo que
hemos obtenido una estimado adicional (y una fila extra, ‘x1’)</p></li>
<li><p>El modelo nos dice que la estimación de ‘x1’ es -0.0366789 y que
no es significativamente diferente de 0 (p = 0.8046743)</p></li>
</ul>
</div>
<hr />
<p> </p>
</div>
<div id="simular-un-predictor-asociado" class="section level2">
<h2>Simular un predictor asociado</h2>
<p>Podemos utilizar la fórmula del modelo lineal anterior para simular
dos variables continuas asociadas así:</p>
<div class="sourceCode" id="cb71"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1"></a><span class="co"># definir semilla</span></span>
<span id="cb71-2"><a href="#cb71-2"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb71-3"><a href="#cb71-3"></a></span>
<span id="cb71-4"><a href="#cb71-4"></a><span class="co"># numero de observaciones</span></span>
<span id="cb71-5"><a href="#cb71-5"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb71-6"><a href="#cb71-6"></a>b0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">4</span></span>
<span id="cb71-7"><a href="#cb71-7"></a>b1 <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb71-8"><a href="#cb71-8"></a>error <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb71-9"><a href="#cb71-9"></a></span>
<span id="cb71-10"><a href="#cb71-10"></a><span class="co"># variables aleatorias</span></span>
<span id="cb71-11"><a href="#cb71-11"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb71-12"><a href="#cb71-12"></a>y <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1 <span class="sc">*</span> x1 <span class="sc">+</span> error</span>
<span id="cb71-13"><a href="#cb71-13"></a></span>
<span id="cb71-14"><a href="#cb71-14"></a><span class="co"># crear data frame</span></span>
<span id="cb71-15"><a href="#cb71-15"></a>xy_datos2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x1, y)</span></code></pre></div>
<p> </p>
<p>Note que <strong>también hemos añadido un término de error</strong>,
por lo que la asociación no es perfecta. Vamos a correr el modelo y
graficar la asociación entre las dos variables:</p>
<div class="sourceCode" id="cb72"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1"></a><span class="co"># construir model</span></span>
<span id="cb72-2"><a href="#cb72-2"></a>xy_mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1, <span class="at">data =</span> xy_datos2)</span>
<span id="cb72-3"><a href="#cb72-3"></a></span>
<span id="cb72-4"><a href="#cb72-4"></a><span class="co"># graficar</span></span>
<span id="cb72-5"><a href="#cb72-5"></a><span class="fu">ggplot</span>(xy_datos2, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y)) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb72-6"><a href="#cb72-6"></a>    <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">geom_point</span>()  <span class="co"># plot points</span></span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-56-1.png" width="672" />
 </p>
<p>La fórmula es la misma que la del modelo anterior:</p>
<center>
<font size = 6><span class="math inline">\(\hat{Y} \sim \beta_{o} +
\beta_{1} * x_{1}\)</span></font>
</center>
<p> </p>
<p>Este es el resumen del modelo:</p>
<div class="sourceCode" id="cb73"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1"></a><span class="fu">summary</span>(xy_mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1, data = xy_datos2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.0133 -1.8718 -0.3698  2.0604  6.3185 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -3.8807     0.4019  -9.656 7.86e-13 ***
## x1            2.8900     0.4425   6.531 3.85e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.805 on 48 degrees of freedom
## Multiple R-squared:  0.4705, Adjusted R-squared:  0.4595 
## F-statistic: 42.65 on 1 and 48 DF,  p-value: 3.854e-08</code></pre>
<p> </p>
<p>.. el gráfico con los tamaños de efecto:</p>
<div class="sourceCode" id="cb75"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1"></a>ci_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">param =</span> <span class="fu">names</span>(xy_mod2<span class="sc">$</span>coefficients), <span class="at">est =</span> xy_mod2<span class="sc">$</span>coefficients,</span>
<span id="cb75-2"><a href="#cb75-2"></a>    <span class="fu">confint</span>(xy_mod2))</span>
<span id="cb75-3"><a href="#cb75-3"></a></span>
<span id="cb75-4"><a href="#cb75-4"></a><span class="fu">ggplot</span>(ci_df, <span class="fu">aes</span>(<span class="at">x =</span> param, <span class="at">y =</span> est)) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>,</span>
<span id="cb75-5"><a href="#cb75-5"></a>    <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> X2.<span class="dv">5</span>.., <span class="at">ymax =</span> X97.<span class="dv">5</span>..)) <span class="sc">+</span></span>
<span id="cb75-6"><a href="#cb75-6"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Parámetro&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tamaño de efecto&quot;</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-58-1.png" width="672" />
 </p>
<p>… y los gráficos diagnósticos del modelo:</p>
<div class="sourceCode" id="cb76"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1"></a><span class="fu">plot_model</span>(xy_mod2, <span class="at">type =</span> <span class="st">&quot;diag&quot;</span>)</span></code></pre></div>
<pre><code>## [[1]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-59-1.png" width="80%" /></p>
<pre><code>## 
## [[2]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-59-2.png" width="80%" /></p>
<pre><code>## 
## [[3]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-59-3.png" width="80%" />
 </p>
<div class="alert alert-success">
<p> </p>
<center>
<font size="5"><b>Interpretación del modelo</b></font>
</center>
<p> </p>
<p>Cuadro con los coeficientes (estimados):</p>
<pre><code>##              Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) -3.880679  0.4018848 -9.656198 7.861629e-13
## x1           2.889963  0.4424946  6.531071 3.853652e-08</code></pre>
<ul>
<li><p>El modelo nos dice que <span
class="math inline">\(beta_1\)</span> (el tamaño de efecto de ‘x1’) es
2.8899633 y que es significativamente diferente de 0 (p =
3.8536524^{-8})</p></li>
<li><p>Los valores simulados de los parámetros de regresión pueden
compararse con el resumen del modelo <code>lm()</code> para tener una
idea de la precisión del modelo:</p>
<ul>
<li><span class="math inline">\(\beta_1\)</span> (the effect size of
‘x1’) was set to 3 and was estimated as 2.89 by the model</li>
</ul></li>
</ul>
</div>
<p> </p>
<div class="alert alert-warning">
<center>
<font size="5"><b>Caso de estudio</b></font>
</center>
<p> </p>
<ul>
<li>Keenan EL, Odom KJ, Araya-Salas M, Horton KG, Strimas-Mackey M,
Meatte MA, Mann NI, Slater PJ, Price JJ, and Templeton CN. 2020. <a
href="https://royalsocietypublishing.org/doi/pdf/10.1098/rspb.2020.2482"><strong>Breeding
season length predicts duet coordination and consistency in Neotropical
wrens (Troglodytidae)</strong></a>. <em>Proceeding of the Royal Society
B</em>. 20202482</li>
</ul>
<p><img src="images/duets.png" width="100%" style="display: block; margin: auto;" />
 </p>
<p>“<em>… la coordinación y la consistencia de los duetos son mayores en
las especies con temporadas de apareamiento especialmente
largas.</em>”</p>
<p><img src="images/duet_reg.png" width="70%" style="display: block; margin: auto;" />
 </p>
</div>
<p> </p>
<div class="alert alert-info">
<p><font size="5">Ejercicio 4</font></p>
<p> </p>
<ul>
<li><p>Aumente el tamaño de la muestra (<code>n</code>) a 1000 o
más</p></li>
<li><p>¿Cómo cambiaron los estimados del tamaño de efecto (<span
class="math inline">\(\beta\)</span>)?</p></li>
<li><p>¿Cómo cambió el error estándar del tamaño de efecto?</p></li>
<li><p>Ahora cambie <code>n</code> a 15 y compruebe de nuevo las
estimaciones del modelo (esta vez compruebe también el valor p)</p></li>
</ul>
</div>
<p> </p>
<hr />
</div>
<div id="varios-predictores-regresión-múltiple" class="section level2">
<h2>Varios predictores: regresión múltiple</h2>
<p>La regresión lineal múltiple es una extensión del modelo de regresión
lineal simple que puede tomar varios predictores:</p>
<center>
<font size = 6><span class="math inline">\(\hat{Y} \sim \beta_{o} +
\beta_{1} * x_{1} + \cdots + \beta_{n} * x_{n}\)</span></font>
</center>
<p> </p>
<p>La fórmula parece compleja, pero sólo quiere decir que cualquier
parámetro adicional tendrá su propia estimación (<span
class="math inline">\(\beta\)</span>). La fórmula para una regresión
lineal de dos predictores se ve así:</p>
<center>
<font size = 6><span class="math inline">\(\hat{Y} \sim \beta_{o} +
\beta_{1} * x_{1} + \beta_{2} * x_{2}\)</span></font>
</center>
<p> </p>
<p>… y se puede simular así:</p>
<div class="sourceCode" id="cb81"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1"></a><span class="co"># semila</span></span>
<span id="cb81-2"><a href="#cb81-2"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb81-3"><a href="#cb81-3"></a></span>
<span id="cb81-4"><a href="#cb81-4"></a><span class="co"># numero de observaciones</span></span>
<span id="cb81-5"><a href="#cb81-5"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb81-6"><a href="#cb81-6"></a>b0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">4</span></span>
<span id="cb81-7"><a href="#cb81-7"></a>b1 <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb81-8"><a href="#cb81-8"></a>b2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span></span>
<span id="cb81-9"><a href="#cb81-9"></a>error <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb81-10"><a href="#cb81-10"></a></span>
<span id="cb81-11"><a href="#cb81-11"></a><span class="co"># variables aleatorias</span></span>
<span id="cb81-12"><a href="#cb81-12"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb81-13"><a href="#cb81-13"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb81-14"><a href="#cb81-14"></a>y <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1 <span class="sc">*</span> x1 <span class="sc">+</span> b2 <span class="sc">*</span> x2 <span class="sc">+</span> error</span>
<span id="cb81-15"><a href="#cb81-15"></a></span>
<span id="cb81-16"><a href="#cb81-16"></a><span class="co"># crear un data frame</span></span>
<span id="cb81-17"><a href="#cb81-17"></a>xy_datos_multp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x1, x2, y)</span>
<span id="cb81-18"><a href="#cb81-18"></a></span>
<span id="cb81-19"><a href="#cb81-19"></a><span class="co"># construir el modelo</span></span>
<span id="cb81-20"><a href="#cb81-20"></a>xy_mod_multp <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> xy_datos_multp)</span>
<span id="cb81-21"><a href="#cb81-21"></a></span>
<span id="cb81-22"><a href="#cb81-22"></a><span class="fu">summary</span>(xy_mod_multp)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1 + x2, data = xy_datos_multp)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.9861 -1.8931 -0.3633  2.0017  6.4127 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -3.8652     0.4169  -9.270 3.49e-12 ***
## x1            2.9015     0.4526   6.411 6.41e-08 ***
## x2           -1.9324     0.4142  -4.665 2.59e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.833 on 47 degrees of freedom
## Multiple R-squared:  0.6116, Adjusted R-squared:  0.595 
## F-statistic:    37 on 2 and 47 DF,  p-value: 2.234e-10</code></pre>
<p> </p>
<p>… graficar los tamaños de efecto:</p>
<div class="sourceCode" id="cb83"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1"></a>ci_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">param =</span> <span class="fu">names</span>(xy_mod_multp<span class="sc">$</span>coefficients), <span class="at">est =</span> xy_mod_multp<span class="sc">$</span>coefficients,</span>
<span id="cb83-2"><a href="#cb83-2"></a>    <span class="fu">confint</span>(xy_mod_multp))</span>
<span id="cb83-3"><a href="#cb83-3"></a></span>
<span id="cb83-4"><a href="#cb83-4"></a><span class="fu">ggplot</span>(ci_df, <span class="fu">aes</span>(<span class="at">x =</span> param, <span class="at">y =</span> est)) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>,</span>
<span id="cb83-5"><a href="#cb83-5"></a>    <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> X2.<span class="dv">5</span>.., <span class="at">ymax =</span> X97.<span class="dv">5</span>..)) <span class="sc">+</span></span>
<span id="cb83-6"><a href="#cb83-6"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Parámetro&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tamaño de efecto&quot;</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-64-1.png" width="672" />
 </p>
<p>… y los gráficos diagnósticos:</p>
<div class="sourceCode" id="cb84"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1"></a><span class="fu">plot_model</span>(xy_mod_multp, <span class="at">type =</span> <span class="st">&quot;diag&quot;</span>)</span></code></pre></div>
<pre><code>## [[1]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-65-1.png" width="80%" /></p>
<pre><code>## 
## [[2]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-65-2.png" width="80%" /></p>
<pre><code>## 
## [[3]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-65-3.png" width="80%" />
 </p>
<div class="alert alert-success">
<p> </p>
<center>
<font size="5"><b>Interpretación del modelo</b></font>
</center>
<p> </p>
<p>Cuadro con los coeficientes (estimados):</p>
<pre><code>##              Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) -3.865192  0.4169493 -9.270172 3.485630e-12
## x1           2.901499  0.4525965  6.410785 6.413676e-08
## x2          -1.932353  0.4142204 -4.665035 2.585128e-05</code></pre>
<ul>
<li><p>El modelo encontró que <span
class="math inline">\(\beta_1\)</span> (el tamaño de efecto de ‘x1’) es
2.9014993 y que es significativamente diferente de 0 (p =
6.4136764^{-8})</p></li>
<li><p>También se encontró que el <span
class="math inline">\(\beta_2\)</span> (el tamaño de efecto de ‘x2’) es
-1.9323526 y que también es significativamente diferente de 0 (p =
2.5851282^{-5})</p></li>
<li><p>Los valores simulados de los parámetros de regresión pueden
compararse con el resumen del modelo <code>lm()</code> para tener una
idea de la precisión del modelo:</p>
<ul>
<li><p><span class="math inline">\(\beta_1\)</span> se fijó en 3 y se
estimó como 2.901.</p></li>
<li><p><span class="math inline">\(\beta_2\)</span> (el tamaño de efecto
de ‘x2’) se fijó en -2 y se estimó como -1.932.</p></li>
</ul></li>
</ul>
</div>
<p> </p>
<div class="alert alert-warning">
<center>
<font size="5"><b>Caso de estudio</b></font>
</center>
<p> </p>
<ul>
<li>Araya-Salas M, P González-Gómez, K Wojczulanis-Jakubas, V López III
&amp; T Wright. 2018. <a
href="https://www.nature.com/articles/s41598-018-20441-x"><strong>Spatial
memory is as important as weapon and body size for territorial ownership
in a lekking hummingbird</strong></a>. <em>Scientific Reports</em>. 13,
e0189969</li>
</ul>
<p>“<em>La memoria espacial, el tamaño corporal y el largo de la punta
del pico … predijeron positivamente la probabilidad de adquirir y
defender un territorio.</em>”</p>
<p><img src="images/lbh_cognition.png" width="100%" style="display: block; margin: auto;" />
 </p>
</div>
<p> </p>
<div class="alert alert-info">
<p><font size="5">Ejercicio 5</font></p>
<p> </p>
<ul>
<li><p>Modifique uno de los tamaños de efecto (<span
class="math inline">\(\beta\)</span>) a 0 (o muy cerca de 0) y corra de
nuevo el modelo y su resumen</p></li>
<li><p>¿Cómo ha cambiado el valor de p?</p></li>
<li><p>Simule un escenario con dos predictores en el que sólo uno de
ellos esté asociado a la respuesta</p></li>
</ul>
</div>
<p> </p>
<p>Hay un punto importante que es necesario enfatizar aquí: <strong>La
regresión múltiple estima el efecto de un predictor después de tener en
cuenta el efecto de los demás predictores del modelo</strong>. En otras
palabras, los nuevos predictores del modelo tratarán de explicar la
variación de los datos que no fue explicada por los otros predictores.
Así que <strong>el resultado de la regresión múltiple no es equivalente
a los resultados de las regresiones lineales simples</strong> sobre los
mismos predictores. Esto puede demostrarse fácilmente corriendo esas
regresiones:</p>
<div class="sourceCode" id="cb89"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1"></a><span class="co"># construir modelos</span></span>
<span id="cb89-2"><a href="#cb89-2"></a>x1y_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1, <span class="at">data =</span> xy_datos)</span>
<span id="cb89-3"><a href="#cb89-3"></a>x2y_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x2, <span class="at">data =</span> xy_datos)</span>
<span id="cb89-4"><a href="#cb89-4"></a></span>
<span id="cb89-5"><a href="#cb89-5"></a><span class="co"># atajo a los coeficientes</span></span>
<span id="cb89-6"><a href="#cb89-6"></a><span class="fu">coef</span>(xy_mod)</span></code></pre></div>
<pre><code>## (Intercept)          x1 
##  0.03977364 -0.03667889</code></pre>
<div class="sourceCode" id="cb91"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1"></a><span class="fu">coef</span>(x1y_mod)</span></code></pre></div>
<pre><code>## (Intercept)          x1 
##  0.03977364 -0.03667889</code></pre>
<div class="sourceCode" id="cb93"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1"></a><span class="fu">coef</span>(x2y_mod)</span></code></pre></div>
<pre><code>## (Intercept)          x2 
##  0.04131955  0.02723902</code></pre>
<p> </p>
<p>Las estimaciones de las mismas variables varían considerablemente
entre la regresión múltiple y las regresiones de un solo predictor.</p>
<p>Este punto se demuestra además por el hecho de que, si uno de los
predictores no tiene ninguna influencia en la respuesta, el efecto del
predictor adicional convergerá a su efecto en una regresión lineal
simple. Para simular este escenario, fijamos b2 en 0:</p>
<div class="sourceCode" id="cb95"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1"></a><span class="co"># definir semilla</span></span>
<span id="cb95-2"><a href="#cb95-2"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb95-3"><a href="#cb95-3"></a></span>
<span id="cb95-4"><a href="#cb95-4"></a><span class="co"># numero de observaciones</span></span>
<span id="cb95-5"><a href="#cb95-5"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb95-6"><a href="#cb95-6"></a>b0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">4</span></span>
<span id="cb95-7"><a href="#cb95-7"></a>b1 <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb95-8"><a href="#cb95-8"></a>b2 <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb95-9"><a href="#cb95-9"></a>error <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb95-10"><a href="#cb95-10"></a></span>
<span id="cb95-11"><a href="#cb95-11"></a><span class="co"># variables aleatorias</span></span>
<span id="cb95-12"><a href="#cb95-12"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb95-13"><a href="#cb95-13"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb95-14"><a href="#cb95-14"></a>y <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1 <span class="sc">*</span> x1 <span class="sc">+</span> b2 <span class="sc">*</span> x2 <span class="sc">+</span> error</span>
<span id="cb95-15"><a href="#cb95-15"></a></span>
<span id="cb95-16"><a href="#cb95-16"></a><span class="co"># crear data frame</span></span>
<span id="cb95-17"><a href="#cb95-17"></a>xy_datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x1, x2, y)</span>
<span id="cb95-18"><a href="#cb95-18"></a></span>
<span id="cb95-19"><a href="#cb95-19"></a><span class="co"># construir modelos</span></span>
<span id="cb95-20"><a href="#cb95-20"></a>xy_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> xy_datos)</span>
<span id="cb95-21"><a href="#cb95-21"></a>x1y_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1, <span class="at">data =</span> xy_datos)</span>
<span id="cb95-22"><a href="#cb95-22"></a></span>
<span id="cb95-23"><a href="#cb95-23"></a><span class="co"># shortcut to coefficients</span></span>
<span id="cb95-24"><a href="#cb95-24"></a><span class="fu">coef</span>(xy_mod)</span></code></pre></div>
<pre><code>## (Intercept)          x1          x2 
## -3.95506411  2.96716643  0.02254914</code></pre>
<div class="sourceCode" id="cb97"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1"></a><span class="fu">coef</span>(x1y_mod)</span></code></pre></div>
<pre><code>## (Intercept)          x1 
##   -3.960226    2.963321</code></pre>
<p>El estimado de <span class="math inline">\(\beta_1\)</span> fue casi
el mismo en la regresión múltiple (2.9671664) y en la regresión de un
solo predictor (2.9633211)</p>
<p>Por comodidad, hemos utilizado <code>coef()</code> para extraer sólo
los estimado de la regresión, pero los valores son los mismos que
obtenemos con <code>summary(model)</code>.</p>
<hr />
</div>
<div id="añadir-un-predictor-categórico" class="section level2">
<h2>Añadir un predictor categórico</h2>
<p>Para los predictores categóricos podemos crear primero una variable
binaria (0, 1) y luego añadir etiquetas a cada valor:</p>
<div class="sourceCode" id="cb99"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1"></a><span class="co"># definir semilla</span></span>
<span id="cb99-2"><a href="#cb99-2"></a><span class="fu">set.seed</span>(<span class="dv">13</span>)</span>
<span id="cb99-3"><a href="#cb99-3"></a></span>
<span id="cb99-4"><a href="#cb99-4"></a><span class="co"># numero de observaciones</span></span>
<span id="cb99-5"><a href="#cb99-5"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb99-6"><a href="#cb99-6"></a>b0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">3</span></span>
<span id="cb99-7"><a href="#cb99-7"></a>b1 <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb99-8"><a href="#cb99-8"></a>error <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb99-9"><a href="#cb99-9"></a></span>
<span id="cb99-10"><a href="#cb99-10"></a><span class="co"># variables aleatorias</span></span>
<span id="cb99-11"><a href="#cb99-11"></a>x1_num <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb99-12"><a href="#cb99-12"></a>y <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1 <span class="sc">*</span> x1_num <span class="sc">+</span> error</span>
<span id="cb99-13"><a href="#cb99-13"></a></span>
<span id="cb99-14"><a href="#cb99-14"></a>x1 <span class="ot">&lt;-</span> <span class="fu">factor</span>(x1_num, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>))</span>
<span id="cb99-15"><a href="#cb99-15"></a></span>
<span id="cb99-16"><a href="#cb99-16"></a><span class="co"># crear data frame</span></span>
<span id="cb99-17"><a href="#cb99-17"></a>xy_datos_cat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x1, x1_num, y)</span>
<span id="cb99-18"><a href="#cb99-18"></a></span>
<span id="cb99-19"><a href="#cb99-19"></a><span class="fu">head</span>(xy_datos_cat)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
x1
</th>
<th style="text-align:center;">
x1_num
</th>
<th style="text-align:center;">
y
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0.6630
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
-3.8408
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2.3255
</td>
</tr>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
-0.4380
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0.4276
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
-1.7534
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>Y así es como se escribe formalmente:</p>
<center>
<font size = 6><span class="math inline">\(\hat{Y} \sim \beta_{o} +
\beta_{1} * x_{1}\)</span></font>
</center>
<p> </p>
<p>Lo mismo que con los predictores continuos.</p>
<p>Podemos explorar el patrón de los datos utilizando un diagrama de
cajas (boxplot):</p>
<div class="sourceCode" id="cb100"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1"></a><span class="co"># graficar</span></span>
<span id="cb100-2"><a href="#cb100-2"></a><span class="fu">ggplot</span>(xy_datos_cat, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-71-1.png" width="672" />
 </p>
<p>… y obtener los estimados del modelo:</p>
<div class="sourceCode" id="cb101"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1"></a><span class="co"># construir modelos</span></span>
<span id="cb101-2"><a href="#cb101-2"></a>xy_mod_cat <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1, <span class="at">data =</span> xy_datos_cat)</span>
<span id="cb101-3"><a href="#cb101-3"></a></span>
<span id="cb101-4"><a href="#cb101-4"></a><span class="fu">summary</span>(xy_mod_cat)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1, data = xy_datos_cat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.8977 -1.9092 -0.0936  1.8090  5.5059 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -2.9974     0.5583  -5.369 2.27e-06 ***
## x1b           1.8140     0.8416   2.155   0.0362 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.954 on 48 degrees of freedom
## Multiple R-squared:  0.08825,    Adjusted R-squared:  0.06925 
## F-statistic: 4.646 on 1 and 48 DF,  p-value: 0.03617</code></pre>
<p> </p>
<p>… graficar los tamaños de efecto:</p>
<div class="sourceCode" id="cb103"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1"></a>ci_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">param =</span> <span class="fu">names</span>(xy_mod_cat<span class="sc">$</span>coefficients), <span class="at">est =</span> xy_mod_cat<span class="sc">$</span>coefficients,</span>
<span id="cb103-2"><a href="#cb103-2"></a>    <span class="fu">confint</span>(xy_mod_cat))</span>
<span id="cb103-3"><a href="#cb103-3"></a></span>
<span id="cb103-4"><a href="#cb103-4"></a><span class="fu">ggplot</span>(ci_df, <span class="fu">aes</span>(<span class="at">x =</span> param, <span class="at">y =</span> est)) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>,</span>
<span id="cb103-5"><a href="#cb103-5"></a>    <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> X2.<span class="dv">5</span>.., <span class="at">ymax =</span> X97.<span class="dv">5</span>..)) <span class="sc">+</span></span>
<span id="cb103-6"><a href="#cb103-6"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Parámetro&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tamaño de efecto&quot;</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-73-1.png" width="672" />
 </p>
<p>… y los gráficos diagnósticos del modelo:</p>
<div class="sourceCode" id="cb104"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1"></a><span class="fu">plot_model</span>(xy_mod_cat, <span class="at">type =</span> <span class="st">&quot;diag&quot;</span>)[[<span class="dv">2</span>]]</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-74-1.png" width="80%" />
 </p>
<div class="alert alert-success">
<p> </p>
<center>
<font size="5"><b>Interpretación del modelo</b></font>
</center>
<p> </p>
<p>Cuadro con los coeficientes (estimados):</p>
<pre><code>##              Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) -2.997415  0.5582513 -5.369293 2.267724e-06
## x1b          1.813997  0.8415955  2.155426 3.617227e-02</code></pre>
<ul>
<li><p>El modelo encontró que <span
class="math inline">\(\beta_1\)</span> (el tamaño de efecto de ‘x1’) es
1.8139973 y que es significativamente diferente de 0 (p =
0.0361723)</p></li>
<li><p>Los valores simulados de los parámetros de regresión pueden
compararse con el resumen del modelo <code>lm()</code> para tener una
idea de la precisión del modelo:</p>
<ul>
<li><span class="math inline">\(\beta_1\)</span> se fijó en 2 y se
estimó como 1.814.</li>
</ul></li>
<li><p>Tenga en cuenta que en este caso el intercepto se refiere a la
estimación del nivel ‘a’ en el predictor categórico, que se utilizó como
base:</p></li>
</ul>
<div class="sourceCode" id="cb106"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1"></a><span class="co"># plot</span></span>
<span id="cb106-2"><a href="#cb106-2"></a><span class="fu">ggplot</span>(xy_datos_cat, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> xy_mod_cat<span class="sc">$</span>coefficients[<span class="dv">1</span>],</span>
<span id="cb106-3"><a href="#cb106-3"></a>    <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-77-1.png" width="672" /></p>
<ul>
<li>Por lo tanto, el intercepto es el mismo que la media de <em>y</em>
para la categoría ‘a’:</li>
</ul>
<div class="sourceCode" id="cb107"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1"></a><span class="fu">mean</span>(xy_datos_cat<span class="sc">$</span>y[xy_datos_cat<span class="sc">$</span>x1 <span class="sc">==</span> <span class="st">&quot;a&quot;</span>])</span></code></pre></div>
<pre><code>## [1] -2.997415</code></pre>
<ul>
<li>Observe también que la etiqueta del estimado es ‘x1b’, no ‘x1’ como
en los predictores continuos. Esto se debe a que en este caso el
estimado se refiere a la diferencia entre los dos niveles de la variable
categórica (‘a’ y ‘b’). Más concretamente, nos dice que en promedio las
observaciones de la categoría ‘b’ son 1.814 más altas que las
observaciones de la categoría ‘a’.</li>
</ul>
<p> </p>
</div>
<p> </p>
<div class="alert alert-warning">
<center>
<font size="5"><b>Caso de estudio</b></font>
</center>
<p> </p>
<ul>
<li>Rico-Guevara A, &amp; M Araya-Salas. 2015. <a
href="https://academic.oup.com/beheco/article/26/1/21/2262689"><strong>Bills
as daggers? A test for sexually dimorphic weapons in a lekking
hummingbird species</strong></a>. <em>Behavioral Ecology</em>. 26 (1):
21-29.</li>
</ul>
<p>“<em>Los machos con puntas de pico más grandes y puntiagudas tuvieron
más éxito en ganar control de territorios en el lek.</em>”</p>
<p><img src="images/daggers_lbh.png" width="75%" style="display: block; margin: auto;" />
 </p>
</div>
<p> </p>
<div class="alert alert-info">
<p><font size="5">Ejercicio 6</font></p>
<p> </p>
<ul>
<li>Los datos desbalanceados cuando hay categorías (es decir, algunas
categorías tienen muchas más observaciones que otras) pueden ser
problemáticos para la inferencia estadística. Modifique el código <a
href="#cb99-1">arriba</a> para simular un juego de datos muy
desbalanceado y compruebe la precisión del modelo.</li>
</ul>
</div>
<hr />
<div class="alert alert-warning">
<font size = 6>
<center>
Variables indicadoras (Dummy variables)
</center>
<p></font></p>
<p>En un modelo de regresión, los predictores categóricos también se
representan como vectores numéricos. Más concretamente, los predictores
categóricos se codifican como 0s y 1s, en los que 1 significa “pertenece
a la misma categoría” y 0 “pertenece a una categoría diferente”.
Mantuvimos el vector numérico original (‘x1_num’) al simular el juego de
datos con el predictor categórico:</p>
<div class="sourceCode" id="cb109"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1"></a><span class="fu">head</span>(xy_datos_cat)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
x1
</th>
<th style="text-align:center;">
x1_num
</th>
<th style="text-align:center;">
y
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0.6630
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
-3.8408
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2.3255
</td>
</tr>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
-0.4380
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0.4276
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
-1.7534
</td>
</tr>
</tbody>
</table>
<p>Observe que las “b” de la columna “x1” se convierten en 1 en la
columna “x1_num” y las “a” se convierten en 0. Esto se denomina variable
indicadora y el proceso se conoce como ‘codificación indicadora’ (dummy
coding).</p>
<p>En realidad, podemos utilizar el vector numérico en el modelo de
regresión y obtener exactamente los mismos resultados:</p>
<div class="sourceCode" id="cb110"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1"></a><span class="co"># summary model with categorical variable</span></span>
<span id="cb110-2"><a href="#cb110-2"></a><span class="fu">summary</span>(xy_mod_cat)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##              Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) -2.997415  0.5582513 -5.369293 2.267724e-06
## x1b          1.813997  0.8415955  2.155426 3.617227e-02</code></pre>
<div class="sourceCode" id="cb112"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1"></a><span class="co"># construir modelos with dummy variable</span></span>
<span id="cb112-2"><a href="#cb112-2"></a>xy_mod_num <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1_num, <span class="at">data =</span> xy_datos_cat)</span>
<span id="cb112-3"><a href="#cb112-3"></a></span>
<span id="cb112-4"><a href="#cb112-4"></a><span class="co"># summary with dummy coding</span></span>
<span id="cb112-5"><a href="#cb112-5"></a><span class="fu">summary</span>(xy_mod_num)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##              Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) -2.997415  0.5582513 -5.369293 2.267724e-06
## x1_num       1.813997  0.8415955  2.155426 3.617227e-02</code></pre>
<p> </p>
<p>Las cosas se complican un poco más cuando se codifica un predictor
categórico con más de dos niveles. Pero la lógica es la misma.</p>
</div>
<p> </p>
<hr />
</div>
<div id="interacciones" class="section level2">
<h2>Interacciones</h2>
<p>Una interacción estadística se refiere a un efecto de una variable
predictora que está mediado por una segunda variable.</p>
<center>
<font size = 6><span class="math inline">\(\hat{Y} \sim \beta_{o} +
\beta_{1} * x_{1} + \beta_{2} * x_{2} + \beta_{3} * x_{1} *
x_{2}\)</span></font>
</center>
<p> </p>
<p>Esto es más fácil de entender si se observa la interacción de una
variable continua y una binaria:</p>
<div class="sourceCode" id="cb114"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1"></a><span class="co"># definir semilla</span></span>
<span id="cb114-2"><a href="#cb114-2"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb114-3"><a href="#cb114-3"></a></span>
<span id="cb114-4"><a href="#cb114-4"></a><span class="co"># numero de observaciones</span></span>
<span id="cb114-5"><a href="#cb114-5"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb114-6"><a href="#cb114-6"></a>b0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">4</span></span>
<span id="cb114-7"><a href="#cb114-7"></a>b1 <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb114-8"><a href="#cb114-8"></a>b2 <span class="ot">&lt;-</span> <span class="fl">1.7</span></span>
<span id="cb114-9"><a href="#cb114-9"></a>b3 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">3</span></span>
<span id="cb114-10"><a href="#cb114-10"></a>error <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb114-11"><a href="#cb114-11"></a></span>
<span id="cb114-12"><a href="#cb114-12"></a><span class="co"># variables aleatorias</span></span>
<span id="cb114-13"><a href="#cb114-13"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="at">n =</span> n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span>
<span id="cb114-14"><a href="#cb114-14"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb114-15"><a href="#cb114-15"></a></span>
<span id="cb114-16"><a href="#cb114-16"></a><span class="co"># interaccion se añade como el producto dex1 y x2</span></span>
<span id="cb114-17"><a href="#cb114-17"></a>y <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1 <span class="sc">*</span> x1 <span class="sc">+</span> b2 <span class="sc">*</span> x2 <span class="sc">+</span> b3 <span class="sc">*</span> x1 <span class="sc">*</span> x2 <span class="sc">+</span> error</span>
<span id="cb114-18"><a href="#cb114-18"></a></span>
<span id="cb114-19"><a href="#cb114-19"></a>x1 <span class="ot">&lt;-</span> <span class="fu">factor</span>(x1, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>))</span>
<span id="cb114-20"><a href="#cb114-20"></a></span>
<span id="cb114-21"><a href="#cb114-21"></a><span class="co"># crear data frame</span></span>
<span id="cb114-22"><a href="#cb114-22"></a>xy_datos_intr <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x1, x2, y)</span>
<span id="cb114-23"><a href="#cb114-23"></a></span>
<span id="cb114-24"><a href="#cb114-24"></a><span class="fu">head</span>(xy_datos_intr)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
x1
</th>
<th style="text-align:center;">
x2
</th>
<th style="text-align:center;">
y
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
1.0256
</td>
<td style="text-align:center;">
-4.0147
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
-0.2848
</td>
<td style="text-align:center;">
-5.1746
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
-1.2207
</td>
<td style="text-align:center;">
-1.3991
</td>
</tr>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
0.1813
</td>
<td style="text-align:center;">
-1.0242
</td>
</tr>
<tr>
<td style="text-align:center;">
a
</td>
<td style="text-align:center;">
-0.1389
</td>
<td style="text-align:center;">
-3.8483
</td>
</tr>
<tr>
<td style="text-align:center;">
b
</td>
<td style="text-align:center;">
0.0058
</td>
<td style="text-align:center;">
4.1377
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb115"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1"></a><span class="co"># construir modelos</span></span>
<span id="cb115-2"><a href="#cb115-2"></a>xy_mod_intr <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x1 <span class="sc">*</span> x2, <span class="at">data =</span> xy_datos_intr)</span>
<span id="cb115-3"><a href="#cb115-3"></a></span>
<span id="cb115-4"><a href="#cb115-4"></a><span class="co"># guardar resumen para graficar lineas de mejor ajuste</span></span>
<span id="cb115-5"><a href="#cb115-5"></a>xy_summ_intr <span class="ot">&lt;-</span> <span class="fu">summary</span>(xy_mod_intr)</span>
<span id="cb115-6"><a href="#cb115-6"></a></span>
<span id="cb115-7"><a href="#cb115-7"></a>xy_summ_intr</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1 + x2 + x1 * x2, data = xy_datos_intr)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.2220 -1.6639 -0.1575  1.6503  6.3832 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -4.1930     0.5702  -7.353 2.70e-09 ***
## x1b           3.5974     0.8061   4.463 5.19e-05 ***
## x2            1.3274     0.6816   1.947  0.05761 .  
## x1b:x2       -2.9720     0.9623  -3.089  0.00341 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.828 on 46 degrees of freedom
## Multiple R-squared:  0.3959, Adjusted R-squared:  0.3565 
## F-statistic: 10.05 on 3 and 46 DF,  p-value: 3.291e-05</code></pre>
<p>También ayuda graficar los datos:</p>
<div class="sourceCode" id="cb117"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1"></a><span class="co"># plot</span></span>
<span id="cb117-2"><a href="#cb117-2"></a><span class="fu">ggplot</span>(<span class="at">data =</span> xy_datos_intr, <span class="fu">aes</span>(<span class="at">x =</span> x2, <span class="at">y =</span> y, <span class="at">color =</span> x1)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb117-3"><a href="#cb117-3"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-85-1.png" width="80%" />
 </p>
<p>… y los tamaños de efecto:</p>
<div class="sourceCode" id="cb118"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1"></a>ci_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">param =</span> <span class="fu">names</span>(xy_mod_intr<span class="sc">$</span>coefficients), <span class="at">est =</span> xy_mod_intr<span class="sc">$</span>coefficients,</span>
<span id="cb118-2"><a href="#cb118-2"></a>    <span class="fu">confint</span>(xy_mod_intr))</span>
<span id="cb118-3"><a href="#cb118-3"></a></span>
<span id="cb118-4"><a href="#cb118-4"></a><span class="fu">ggplot</span>(ci_df, <span class="fu">aes</span>(<span class="at">x =</span> param, <span class="at">y =</span> est)) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>,</span>
<span id="cb118-5"><a href="#cb118-5"></a>    <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> X2.<span class="dv">5</span>.., <span class="at">ymax =</span> X97.<span class="dv">5</span>..)) <span class="sc">+</span></span>
<span id="cb118-6"><a href="#cb118-6"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Parámetro&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tamaño de efecto&quot;</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-86-1.png" width="672" />
 </p>
<p>También deberíamos revisar los gráficos de diagnóstico:</p>
<div class="sourceCode" id="cb119"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1"></a><span class="fu">plot_model</span>(xy_mod_intr, <span class="at">type =</span> <span class="st">&quot;diag&quot;</span>)</span></code></pre></div>
<pre><code>## [[1]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-87-1.png" width="80%" /></p>
<pre><code>## 
## [[2]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-87-2.png" width="80%" /></p>
<pre><code>## 
## [[3]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-87-3.png" width="80%" /></p>
<pre><code>## 
## [[4]]</code></pre>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-87-4.png" width="80%" />
 </p>
<div class="alert alert-success">
<p> </p>
<center>
<font size="5"><b>Interpretación del modelo</b></font>
</center>
<p> </p>
<p>Cuadro con los coeficientes:</p>
<pre><code>##              Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) -4.193018  0.5702328 -7.353168 2.697816e-09
## x1b          3.597411  0.8060688  4.462908 5.194964e-05
## x2           1.327353  0.6816129  1.947370 5.760963e-02
## x1b:x2      -2.971961  0.9622652 -3.088505 3.406062e-03</code></pre>
<ul>
<li><p>El modelo encontró que <span
class="math inline">\(\beta_1\)</span> (el tamaño de efecto de ‘x1-b’ a
‘x1-a’) es 3.5974112 y que es significativamente diferente de 0 (valor p
= 5.1949639^{-5})</p></li>
<li><p>El modelo encontró que <span
class="math inline">\(\beta_2\)</span> (el tamaño de efecto de ‘x2’) es
1.3273528 y que es significativamente diferente de 0 (p = 0.0576096).
Esto es en realidad la pendiente de la relación entre x2 e y cuando x1 =
`a’</p></li>
<li><p>El modelo encontró que <span
class="math inline">\(\beta_3\)</span> (el tamaño de efecto del término
de interacción ‘x1 * x2’) es -2.9719608 y que es significativamente
diferente de 0 (p = 0.0034061). Esta es la diferencia entre las
pendientes de x2 <em>vs</em> y cuando x1 = ‘a’ y x2 <em>vs</em> y cuando
x1 = ‘b’.</p></li>
<li><p>Los valores simulados para los parámetros de regresión pueden
compararse con el resumen del modelo <code>lm()</code> para tener una
idea de la precisión del modelo:</p>
<ul>
<li><p><span class="math inline">\(\beta_1\)</span> was set to 3 and was
estimated as 3.597</p></li>
<li><p><span class="math inline">\(\beta_2\)</span> was set to 1.7 and
was estimated as 1.327</p></li>
<li><p><span class="math inline">\(\beta_3\)</span> was set to -3 and
was estimated as -2.972</p></li>
</ul></li>
</ul>
</div>
<hr />
<p> </p>
<div class="alert alert-warning">
<center>
<font size="5"><b>Caso de estudio</b></font>
</center>
<p> </p>
<ul>
<li>Chirino F, B Wilink, Araya-Salas M. In prep. <strong>Climatic
factors affecting vocal activity in lemur leaf frogs</strong>.</li>
</ul>
<p>“<em>El aumento de la luz de la luna disminuye la actividad vocal
de</em> Agalychnis lemur <em>aunque esta relación es mediada por la
temperatura.</em>”</p>
<p><img src="images/lemur.png" width="70%" style="display: block; margin: auto;" />
 </p>
</div>
<p> </p>
<div class="alert alert-info">
<p><font size="5">Ejercicio 7</font></p>
<p> </p>
<ul>
<li><p>Modifique el <a href="#simular-un-predictor-asociado">código
usado para simular un único predictor asociado</a> aumentando
gradualmente el error. Esto se hace aumentando el argumento ‘sd’ en
<code>error &lt;- rnorm(n = n, sd = 2)</code>.</p></li>
<li><p>Mire cómo los errores más grandes afectan la inferencia (debe
volver a correr los modelos)</p></li>
<li><p>Ahora reemplace el término de error con
<code>error &lt;- rexp(n = n, rate = 0.2)</code>. Esto crea un error con
una distribución exponencial (por lo tanto no normal). Se supone que
esto es problemático para el poder inferencial de estos modelos. Compare
las estimaciones que obtuvo con los valores de la simulación (‘b0’ y
‘b1’). Explore la distribución de los residuos
(<code>plot(nombre_del_modelo)</code>) para los modelos de error
‘normal’ y ‘exponencial’.</p></li>
<li><p>Se supone que la colinealidad (la presencia de predictores
correlacionados) afecta a la estabilidad de la regresión múltiple. El
siguiente código crea dos predictores altamente colineales (‘x1’ y
‘x2’). La última línea de código muestra la correlación entre
ellos.</p></li>
</ul>
<div class="sourceCode" id="cb125"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1"></a><span class="co"># definir semilla</span></span>
<span id="cb125-2"><a href="#cb125-2"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb125-3"><a href="#cb125-3"></a></span>
<span id="cb125-4"><a href="#cb125-4"></a><span class="co"># numero de observaciones</span></span>
<span id="cb125-5"><a href="#cb125-5"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb125-6"><a href="#cb125-6"></a>b0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">4</span></span>
<span id="cb125-7"><a href="#cb125-7"></a>b1 <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb125-8"><a href="#cb125-8"></a>b2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span></span>
<span id="cb125-9"><a href="#cb125-9"></a>error <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb125-10"><a href="#cb125-10"></a></span>
<span id="cb125-11"><a href="#cb125-11"></a><span class="co"># variables aleatorias</span></span>
<span id="cb125-12"><a href="#cb125-12"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb125-13"><a href="#cb125-13"></a></span>
<span id="cb125-14"><a href="#cb125-14"></a><span class="co"># hacer x2 muy parecido a x1</span></span>
<span id="cb125-15"><a href="#cb125-15"></a>x2 <span class="ot">&lt;-</span> x1 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fl">0.3</span>)</span>
<span id="cb125-16"><a href="#cb125-16"></a></span>
<span id="cb125-17"><a href="#cb125-17"></a><span class="fu">cor</span>(x1, x2)</span></code></pre></div>
<pre><code>## [1] 0.9464161</code></pre>
<ul>
<li><p>Construya un modelo de regresión múltiple para estos datos (y ~
x1 + x2). Puede utilizar el mismo código que en la sección <a
href="#añadir-más-de-un-predictor:-regresión-múltiple">Añadir más de un
predictor: regresión múltiple</a>.</p></li>
<li><p>¿Cómo afecta a la inferencia la presencia de predictores
colineales? Realice los gráficos de diagnóstico para este modelo
(<code>plot(nombre_del_modelo)</code>).</p></li>
<li><p>Simule un juego de datos con tres predictores en los que sólo dos
de ellos son altamente colineales. Ajuste un modelo de regresión
múltiple (y ~ x1 + x2 + x3) para esos datos y observe cómo la
colinealidad afecta a la estimación del predictor no colineal.</p></li>
</ul>
<p> </p>
</div>
<hr />
</div>
</div>
<div
id="extender-los-modelos-lineales-a-estructuras-de-datos-más-complejas"
class="section level1">
<h1>Extender los modelos lineales a estructuras de datos más
complejas</h1>
<p> </p>
<div id="modelos-lineales-generalizados-glm" class="section level2">
<h2>Modelos lineales generalizados (GLM)</h2>
<p>Los GLM nos permiten modelar la asociación a variables respuesta que
no se ajustan a una distribución normal. Además, permiten modelar
distribuciones que se asemejan más al proceso que generó los datos. El
siguiente código crea un juego de datos con una respuesta que representa
cuentas (por lo tanto, no normal):</p>
<div class="sourceCode" id="cb127"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1"></a><span class="co"># definir semilla</span></span>
<span id="cb127-2"><a href="#cb127-2"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb127-3"><a href="#cb127-3"></a></span>
<span id="cb127-4"><a href="#cb127-4"></a><span class="co"># numero de muestas</span></span>
<span id="cb127-5"><a href="#cb127-5"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb127-6"><a href="#cb127-6"></a></span>
<span id="cb127-7"><a href="#cb127-7"></a><span class="co"># coeficientes</span></span>
<span id="cb127-8"><a href="#cb127-8"></a>b0 <span class="ot">&lt;-</span> <span class="fl">1.2</span></span>
<span id="cb127-9"><a href="#cb127-9"></a>b1 <span class="ot">&lt;-</span> <span class="fl">1.3</span></span>
<span id="cb127-10"><a href="#cb127-10"></a>b2 <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb127-11"><a href="#cb127-11"></a></span>
<span id="cb127-12"><a href="#cb127-12"></a></span>
<span id="cb127-13"><a href="#cb127-13"></a><span class="co"># generar variables</span></span>
<span id="cb127-14"><a href="#cb127-14"></a>y <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="at">n =</span> n, <span class="at">lambda =</span> <span class="fl">6.5</span>)  <span class="co"># lambda = tasa promedio de exitos </span></span>
<span id="cb127-15"><a href="#cb127-15"></a>x2 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span>, , <span class="fu">length</span>(y))</span>
<span id="cb127-16"><a href="#cb127-16"></a>x1 <span class="ot">&lt;-</span> (<span class="fu">log</span>(y) <span class="sc">-</span> b0 <span class="sc">-</span> b2 <span class="sc">*</span> x2)<span class="sc">/</span>b1</span>
<span id="cb127-17"><a href="#cb127-17"></a></span>
<span id="cb127-18"><a href="#cb127-18"></a><span class="co"># crear data frame</span></span>
<span id="cb127-19"><a href="#cb127-19"></a>xy_datos_pois <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x1, x2, y)</span>
<span id="cb127-20"><a href="#cb127-20"></a></span>
<span id="cb127-21"><a href="#cb127-21"></a><span class="fu">head</span>(xy_datos_pois)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
x1
</th>
<th style="text-align:center;">
x2
</th>
<th style="text-align:center;">
y
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
0.1433
</td>
<td style="text-align:center;">
-0.5000
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
0.5738
</td>
<td style="text-align:center;">
-0.4796
</td>
<td style="text-align:center;">
7
</td>
</tr>
<tr>
<td style="text-align:center;">
0.5738
</td>
<td style="text-align:center;">
-0.4592
</td>
<td style="text-align:center;">
7
</td>
</tr>
<tr>
<td style="text-align:center;">
0.5738
</td>
<td style="text-align:center;">
-0.4388
</td>
<td style="text-align:center;">
7
</td>
</tr>
<tr>
<td style="text-align:center;">
0.7671
</td>
<td style="text-align:center;">
-0.4184
</td>
<td style="text-align:center;">
9
</td>
</tr>
<tr>
<td style="text-align:center;">
0.5738
</td>
<td style="text-align:center;">
-0.3980
</td>
<td style="text-align:center;">
7
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>También grafiquemos ‘x1’ <em>vs</em> ‘y’:</p>
<div class="sourceCode" id="cb128"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1"></a><span class="co"># graficar</span></span>
<span id="cb128-2"><a href="#cb128-2"></a><span class="fu">ggplot</span>(xy_datos_pois, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-95-1.png" width="672" />
 </p>
<p>La relación no parece muy lineal ni la varianza parece ser constante
a través de ‘x1’.</p>
<p>Podemos relajar el requisito de la distribución normal con GLMs.
<code>glm()</code> es una función básica de R que nos ayuda a hacer el
truco. Para este ejemplo la distribución más apropiada es
<em>Poisson</em>. Esto se puede establecer en el argumento `family’
así:</p>
<div class="sourceCode" id="cb129"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1"></a>glm_pois <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> xy_datos_pois, <span class="at">family =</span> <span class="fu">poisson</span>())</span></code></pre></div>
<p> </p>
<p>Que es equivalente a esto:</p>
<center>
<font size = 6><span class="math inline">\(\hat{Y} \sim_{poisson}
\beta_{o} + \beta_{1} * x_{1} + \beta_{2} * x_{2}\)</span></font>
</center>
<p> </p>
<p>Como puede ver el único argumento extra comparado con
<code>lm()</code> es <code>family</code>. El resto es simplemente la
“fórmula” y los “datos” con los que ya estamos familiarizados. Así que,
de nuevo, podemos aprovechar nuestros conocimientos sobre los modelos
lineales para extenderlos a estructuras de datos más complejas.</p>
<p>También necesitamos ejecutar <code>summary()</code> para obtener el
resultado del modelo:</p>
<div class="sourceCode" id="cb130"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1"></a><span class="fu">summary</span>(glm_pois)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x1 + x2, family = poisson(), data = xy_datos_pois)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## 0.00e+00  0.00e+00  0.00e+00  0.00e+00  2.98e-08  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) 1.200e+00  1.289e-01   9.311  &lt; 2e-16 ***
## x1          1.300e+00  2.196e-01   5.920 3.22e-09 ***
## x2          1.225e-16  1.902e-01   0.000        1    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance:  3.9471e+01  on 49  degrees of freedom
## Residual deviance: -5.9952e-15  on 47  degrees of freedom
## AIC: 186.89
## 
## Number of Fisher Scoring iterations: 3</code></pre>
<p> </p>
<p> </p>
<div class="alert alert-success">
<p> </p>
<center>
<font size="5"><b>Interpretación del modelo</b></font>
</center>
<p> </p>
<p>Cuadro de los coeficientes (estimados):</p>
<pre><code>##                 Estimate Std. Error      z value     Pr(&gt;|z|)
## (Intercept) 1.200000e+00  0.1288851 9.310615e+00 1.270940e-20
## x1          1.300000e+00  0.2195953 5.919980e+00 3.219809e-09
## x2          1.224817e-16  0.1901631 6.440877e-16 1.000000e+00</code></pre>
<ul>
<li><p>El modelo nos dice que <span
class="math inline">\(\beta_1\)</span> (el tamaño de efecto de ‘x1’) es
1.3 y que es significativamente diferente de 0 (p = 3.2198086^{-9}).
Esto se interpreta en realidad como que un aumento de 1 unidad de ‘x1’
resulta en ‘y’ (tasa) en un factor de exp(1.3) = 3.6692967.</p></li>
<li><p>El modelo también nos dice que <span
class="math inline">\(\beta_2\)</span> (el tamaño de efecto de ‘x2’) es
1.2248169^{-16} y que es significativamente diferente de 0 (p = 1). Esto
significa que un aumento en 1 unidad de ‘x2’ resulta en ‘y’ (tasa) en un
factor de exp(1.2248169^{-16}) = 1.</p></li>
</ul>
</div>
<p> </p>
<div class="alert alert-warning">
<center>
<font size="5"><b>Caso de estudio</b></font>
</center>
<p> </p>
<ul>
<li>Topp, E. N., Tscharntke, T., &amp; Loos, J. (2022). <a
href="https://onlinelibrary.wiley.com/doi/pdf/10.1111/ddi.13257"><strong>Fire
and landscape context shape plant and butterfly diversity in a South
African shrubland</strong></a>. <em>Diversity and Distributions</em>,
28(3), 357-371.</li>
</ul>
<p>“<em>La riqueza de especies de mariposas es de tres a cuatro veces
mayor cuando aumenta el hábitat natural en el paisaje circundante (en un
radio de 2 km), mientras que la abundancia de mariposas se asociaba
negativamente con el aumento del tiempo transcurrido desde el último
incendio.</em>”</p>
<p><img src="images/butterflies.png" width="100%" style="display: block; margin: auto;" />
 </p>
</div>
<p> </p>
<div class="alert alert-info">
<p><font size="5">Ejercicio 8</font></p>
<p> </p>
<ul>
<li>Intente correr un modelo <code>lm()</code> (con una distribución
gaussiana), compare los resultados y compruebe los residuos
(<code>plot_model(model_name, type = "diag")</code>)</li>
</ul>
</div>
<p> </p>
<p>Existen muchas otras funciones de distribución y enlace:</p>
<p><img src="images/link-functions.jpg" width="80%" style="display: block; margin: auto;" />
 </p>
<hr />
</div>
<div id="modelos-de-efectos-variables-modelos-mixtos"
class="section level2">
<h2>Modelos de efectos variables (modelos mixtos)</h2>
<p>A veces nuestros conjuntos de datos incluyen estructuras con varios
niveles de organización. Por ejemplo, cuando tomamos muestras de varios
individuos de diferentes poblaciones. En esos casos, la variación en el
nivel estructural superior (poblaciones) podría impedir la detección de
patrones en el nivel inferior (individuos).</p>
<p>Vamos a simular algunos datos que se asemejan a ese escenario.
Tenemos dos predictores continuos (x1) y una respuesta continua (y).
Cada muestra procede de 1 de 8 poblaciones diferentes (poblacion):</p>
<div class="sourceCode" id="cb133"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1"></a><span class="co"># x&lt;- 1 definir semilla</span></span>
<span id="cb133-2"><a href="#cb133-2"></a><span class="fu">set.seed</span>(<span class="dv">28</span>)</span>
<span id="cb133-3"><a href="#cb133-3"></a></span>
<span id="cb133-4"><a href="#cb133-4"></a><span class="co"># numero de observaciones</span></span>
<span id="cb133-5"><a href="#cb133-5"></a>n <span class="ot">&lt;-</span> <span class="dv">300</span></span>
<span id="cb133-6"><a href="#cb133-6"></a>b0 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb133-7"><a href="#cb133-7"></a>b1 <span class="ot">&lt;-</span> <span class="fl">1.3</span></span>
<span id="cb133-8"><a href="#cb133-8"></a>poblacion <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">8</span>, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb133-9"><a href="#cb133-9"></a>error <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb133-10"><a href="#cb133-10"></a></span>
<span id="cb133-11"><a href="#cb133-11"></a><span class="co"># variables aleatorias</span></span>
<span id="cb133-12"><a href="#cb133-12"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb133-13"><a href="#cb133-13"></a>y <span class="ot">&lt;-</span> b0 <span class="sc">+</span> poblacion <span class="sc">*</span> <span class="dv">2</span> <span class="sc">+</span> b1 <span class="sc">*</span> x1 <span class="sc">+</span> error</span>
<span id="cb133-14"><a href="#cb133-14"></a></span>
<span id="cb133-15"><a href="#cb133-15"></a><span class="co"># add letters</span></span>
<span id="cb133-16"><a href="#cb133-16"></a>poblacion <span class="ot">&lt;-</span> letters[poblacion <span class="sc">+</span> <span class="dv">1</span>]</span>
<span id="cb133-17"><a href="#cb133-17"></a></span>
<span id="cb133-18"><a href="#cb133-18"></a><span class="co"># create data set</span></span>
<span id="cb133-19"><a href="#cb133-19"></a>xy_datos_mixto <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x1, y, poblacion)</span>
<span id="cb133-20"><a href="#cb133-20"></a></span>
<span id="cb133-21"><a href="#cb133-21"></a><span class="fu">head</span>(xy_datos_mixto, <span class="dv">10</span>)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
x1
</th>
<th style="text-align:center;">
y
</th>
<th style="text-align:center;">
poblacion
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1.5461
</td>
<td style="text-align:center;">
3.3378
</td>
<td style="text-align:center;">
a
</td>
</tr>
<tr>
<td style="text-align:center;">
0.5683
</td>
<td style="text-align:center;">
3.1400
</td>
<td style="text-align:center;">
a
</td>
</tr>
<tr>
<td style="text-align:center;">
-0.6385
</td>
<td style="text-align:center;">
15.2824
</td>
<td style="text-align:center;">
i
</td>
</tr>
<tr>
<td style="text-align:center;">
0.9842
</td>
<td style="text-align:center;">
2.6610
</td>
<td style="text-align:center;">
a
</td>
</tr>
<tr>
<td style="text-align:center;">
1.0536
</td>
<td style="text-align:center;">
3.7312
</td>
<td style="text-align:center;">
b
</td>
</tr>
<tr>
<td style="text-align:center;">
-0.8229
</td>
<td style="text-align:center;">
3.0189
</td>
<td style="text-align:center;">
a
</td>
</tr>
<tr>
<td style="text-align:center;">
-1.3237
</td>
<td style="text-align:center;">
3.2186
</td>
<td style="text-align:center;">
c
</td>
</tr>
<tr>
<td style="text-align:center;">
2.1785
</td>
<td style="text-align:center;">
19.0542
</td>
<td style="text-align:center;">
i
</td>
</tr>
<tr>
<td style="text-align:center;">
2.2648
</td>
<td style="text-align:center;">
15.4549
</td>
<td style="text-align:center;">
i
</td>
</tr>
<tr>
<td style="text-align:center;">
-0.7784
</td>
<td style="text-align:center;">
11.6670
</td>
<td style="text-align:center;">
h
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>Podemos explorar la relación entre ‘y’ y ‘x1’ con un gráfico:</p>
<div class="sourceCode" id="cb134"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> xy_datos_mixto, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-102-1.png" width="672" />
 </p>
<p>¿Puede ver claramente el patrón de asociación entre las dos variables
que hemos utilizado para simular los datos? Podemos seguir explorando
los datos con un modelo de regresión lineal simple:</p>
<div class="sourceCode" id="cb135"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x1, <span class="at">data =</span> xy_datos_mixto))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1, data = xy_datos_mixto)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.7547  -5.1191   0.1855   4.6016  12.4090 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   8.8520     0.3253  27.214   &lt;2e-16 ***
## x1            0.6332     0.3292   1.924   0.0554 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.628 on 298 degrees of freedom
## Multiple R-squared:  0.01226,    Adjusted R-squared:  0.008949 
## F-statistic:   3.7 on 1 and 298 DF,  p-value: 0.05537</code></pre>
<p> </p>
<p>A pesar de haber simulado un <span
class="math inline">\(\beta_1\)</span> distinto de cero, no tenemos
ninguna asociación significativa según este modelo y la estimación de
<span class="math inline">\(\beta_1\)</span> está muy lejos de la
simulada. Esta pobre inferencia se debe a que estamos ignorando una
característica importante de nuestros datos, la agrupación de las
muestras en “poblaciones”.</p>
<p>Los modelos de efectos mixtos (también conocidos como modelos
multinivel o modelos de efectos variables) pueden ayudarnos a tener en
cuenta estas características adicionales, mejorando significativamente
nuestro poder de inferencia. Coloreemos cada una de las poblaciones para
ver cómo covarían las variables en cada subgrupo de datos:</p>
<div class="sourceCode" id="cb137"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> xy_datos_mixto, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y, <span class="at">color =</span> poblacion)) <span class="sc">+</span></span>
<span id="cb137-2"><a href="#cb137-2"></a>    <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-104-1.png" width="672" />
 </p>
<p>Parece haber un patrón claro de asociación positiva entre x1 e y. El
patrón se hace un poco más evidente si representamos cada población en
su propio panel:</p>
<div class="sourceCode" id="cb138"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> xy_datos_mixto, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y, <span class="at">color =</span> poblacion)) <span class="sc">+</span></span>
<span id="cb138-2"><a href="#cb138-2"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>poblacion) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb138-3"><a href="#cb138-3"></a>    <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="modelos_de_regresion_files/figure-html/unnamed-chunk-105-1.png" width="100%" />
 </p>
<p>Construyamos un modelo de efectos mixtos utilizando la población como
intercepto variable:</p>
<div class="sourceCode" id="cb139"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1"></a>mix_eff_mod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">formula =</span> y <span class="sc">~</span> x1 <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> poblacion), <span class="at">data =</span> xy_datos_mixto)</span></code></pre></div>
<p>Que es equivalente a esto:</p>
<center>
<font size = 6><span class="math inline">\(\hat{Y} \sim_{gausiana}
(\beta_{o} + \beta_{grupo}) + \beta_{1} * x_{1}\)</span></font>
</center>
<p> </p>
<p>Podemos ver el resultado del modelo igual que con un modelo
<code>lm()</code>:</p>
<div class="sourceCode" id="cb140"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1"></a><span class="fu">summary</span>(mix_eff_mod)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: y ~ x1 + (1 | poblacion)
##    Data: xy_datos_mixto
## 
## REML criterion at convergence: 1296.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5236 -0.6575 -0.0316  0.6124  3.2454 
## 
## Random effects:
##  Groups    Name        Variance Std.Dev.
##  poblacion (Intercept) 30.073   5.484   
##  Residual               3.762   1.940   
## Number of obs: 300, groups:  poblacion, 9
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept)   8.7881     1.8315   8.0031   4.798  0.00136 ** 
## x1            1.3166     0.1151 290.0679  11.440  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##    (Intr)
## x1 -0.003</code></pre>
<p> </p>
<p>El modelo detectó correctamente el patrón simulado y la estimación de
<span class="math inline">\(\beta_1\)</span> (1.317) es muy cercana al
valor simulado.</p>
<p> </p>
<div class="alert alert-warning">
<center>
<font size="5"><b>Caso de estudio</b></font>
</center>
<p> </p>
<ul>
<li>Araya-Salas M, P González-Gómez, K Wojczulanis-Jakubas, V López III
&amp; T Wright. 2018. <a
href="https://www.nature.com/articles/s41598-018-20441-x"><strong>Spatial
memory is as important as weapon and body size for territorial ownership
in a lekking hummingbird</strong></a>. <em>Scientific Reports</em>. 13,
e0189969</li>
</ul>
<p>“<em>… el tamaño corporal mostró una correlación negativa con la
frecuencia baja del canto.</em>”</p>
<p><img src="images/lbh_song_size.png" width="80%" style="display: block; margin: auto;" />
 </p>
</div>
<p> </p>
<div class="alert alert-success">
<p> </p>
<center>
<font size="5"><b>Interpretación del modelo</b></font>
</center>
<p> </p>
<p>Cuadro con los coeficientes (estimados):</p>
<pre><code>##             Estimate Std. Error         df   t value     Pr(&gt;|t|)
## (Intercept) 8.788106  1.8314923   8.003127  4.798331 1.356947e-03
## x1          1.316649  0.1150966 290.067879 11.439512 2.932632e-25</code></pre>
<p> </p>
<ul>
<li><p>El modelo encontró que <span
class="math inline">\(\beta_1\)</span> (el tamaño de efecto de ‘x1’) es
1.3166493 y que es significativamente diferente de 0 (p =
2.9326317^{-25})</p></li>
<li><p>Los valores simulados de los parámetros de regresión pueden
compararse con el resumen del modelo <code>lmer()</code> para tener una
idea de la precisión del modelo:</p>
<ul>
<li><span class="math inline">\(\beta_1\)</span> se fijó en 1.3 y se
estimó como 1.317.</li>
</ul></li>
<li><p>La varianza del intercepto para cada población fue de 29.9562355
y la desviación estándar de 5.473229</p></li>
<li><p>Los interceptos estimados para cada población son:</p></li>
</ul>
<div class="sourceCode" id="cb143"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1"></a><span class="fu">ranef</span>(mix_eff_mod)<span class="sc">$</span>poblacion</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
(Intercept)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
-8.2284
</td>
</tr>
<tr>
<td style="text-align:center;">
-6.1713
</td>
</tr>
<tr>
<td style="text-align:center;">
-4.2305
</td>
</tr>
<tr>
<td style="text-align:center;">
-1.3084
</td>
</tr>
<tr>
<td style="text-align:center;">
0.2457
</td>
</tr>
<tr>
<td style="text-align:center;">
2.2255
</td>
</tr>
<tr>
<td style="text-align:center;">
3.9156
</td>
</tr>
<tr>
<td style="text-align:center;">
5.7561
</td>
</tr>
<tr>
<td style="text-align:center;">
7.7957
</td>
</tr>
</tbody>
</table>
<p> </p>
<ul>
<li>Podemos compararlos con los promedios para cada población en los
datos:</li>
</ul>
<div class="sourceCode" id="cb144"><pre
class="sourceCode numberSource r numberLines lineAnchors"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1"></a><span class="co"># sumar interceptos por poblacion a el intercepto total</span></span>
<span id="cb144-2"><a href="#cb144-2"></a>interceptos <span class="ot">&lt;-</span> <span class="fu">ranef</span>(mix_eff_mod)<span class="sc">$</span>poblacion <span class="sc">+</span> <span class="fu">fixef</span>(mix_eff_mod)[<span class="dv">1</span>]</span>
<span id="cb144-3"><a href="#cb144-3"></a></span>
<span id="cb144-4"><a href="#cb144-4"></a><span class="co"># calcular los promedios por poblacion en los datos</span></span>
<span id="cb144-5"><a href="#cb144-5"></a>prom_pobs <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(y <span class="sc">~</span> poblacion, xy_datos_mixto, mean)</span>
<span id="cb144-6"><a href="#cb144-6"></a></span>
<span id="cb144-7"><a href="#cb144-7"></a><span class="co"># unir</span></span>
<span id="cb144-8"><a href="#cb144-8"></a><span class="fu">cbind</span>(interceptos, <span class="at">prom_pobs =</span> prom_pobs[, <span class="dv">2</span>])</span></code></pre></div>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
(Intercept)
</th>
<th style="text-align:center;">
prom_pobs
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
0.5598
</td>
<td style="text-align:center;">
0.8615
</td>
</tr>
<tr>
<td style="text-align:center;">
2.6168
</td>
<td style="text-align:center;">
2.7686
</td>
</tr>
<tr>
<td style="text-align:center;">
4.5576
</td>
<td style="text-align:center;">
4.9011
</td>
</tr>
<tr>
<td style="text-align:center;">
7.4797
</td>
<td style="text-align:center;">
7.7317
</td>
</tr>
<tr>
<td style="text-align:center;">
9.0338
</td>
<td style="text-align:center;">
8.8765
</td>
</tr>
<tr>
<td style="text-align:center;">
11.0136
</td>
<td style="text-align:center;">
10.7765
</td>
</tr>
<tr>
<td style="text-align:center;">
12.7037
</td>
<td style="text-align:center;">
12.6265
</td>
</tr>
<tr>
<td style="text-align:center;">
14.5442
</td>
<td style="text-align:center;">
14.6211
</td>
</tr>
<tr>
<td style="text-align:center;">
16.5838
</td>
<td style="text-align:center;">
16.4252
</td>
</tr>
</tbody>
</table>
<p> </p>
<ul>
<li>La varianza entre los niveles del factor aleatorio
(<code>poblacion</code>) es de 29.9562355 y la desviación estándar de
5.473229</li>
</ul>
<p> </p>
</div>
<p> </p>
<div id="la-paradoja-de-simpson" class="section level3">
<h3>La paradoja de Simpson</h3>
<p>La paradoja de Simpson es un fenómeno en estadística en el que una
tendencia aparece en varios grupos de datos pero desaparece o se
invierte cuando se combinan los grupos. Se ha utilizado para ilustrar el
tipo de resultados engañosos que puede generar el ignorar la estructura
en los datos y las relaciones causales entre variables.</p>
<p><img src="images/simpsons_paradox.gif" width="80%" style="display: block; margin: auto;" /></p>
<p><font size="3">Tomado de wikipedia</font></p>
<p> </p>
<p>La estructura de los datos debido a observaciones pertenecientes al
mismo grupo puede ser tomada en cuenta usando el grupo como un factor
aleatorio, tal y como se hizo en el ejemplo anterior.</p>
<p> </p>
<div class="alert alert-info">
<center>
<b><font size="5">Modelos lineales como abordaje estadístico estándar
</font></b>
</center>
<p><img src="images/swiss_knife.png" width="40%" style="display: block; margin: auto;" /></p>
<center>
<font size = 5><span class="math inline">\(\hat{Y} \sim_{función\ de\
enlace} (\beta_{o} + \beta_{grupo}) + \beta_{1} * x_{1} + \cdots +
\beta_{n} * x_{n}\)</span></font>
</center>
<ul>
<li><p>Este modelo básico incluye una función de enlace que cuando es
gausiana equivale aun modelo linear y cuando no a un modelo
generalizado</p></li>
<li><p>Cuando el <span class="math inline">\(\beta_{grupo}\)</span> es
diferente entre grupos (i.e. cuando el intercepto difiere entre grupos)
es un modelo mixto con intercepto variable (i.e. aleatorio)</p></li>
</ul>
<p> </p>
</div>
<p> </p>
<p>Este manual solo pretende sugerir un abordaje estadístico centrado en
los modelos de regresión desde el cual se pueden llevar a cabo
adecuadamente la mayoría de los análisis estadísticos que usamos en
biología. <strong>El manual no tiene como objetivo explicar en detalle
las particularidades de los modelos generalizados y mixtos</strong>.
Note que estos modelos, principalmente los mixtos, pueden ajustarse a
otras estructuras de datos mas complejas no cubiertas aquí, como lo son
las pendientes aleatorias, pendientes e interceptos aleatorios,
estructuras de correlación (i.e. autocorrelación espacial o temporal,
pedigrís o árboles filogenéticos) y el uso de pseudoreplicas.</p>
<p> </p>
<hr />
</div>
</div>
<div id="referencias" class="section level2">
<h2>Referencias</h2>
<ul>
<li><p><a
href="https://github.com/rmcelreath/stat_rethinking_2022">Richard
McElreath’s Statistical Rethinking book</a></p></li>
<li><p><a
href="https://www.programmingr.com/examples/neat-tricks/sample-r-function/r-rbinom/">R’s
rbinom – Simulate Binomial or Bernoulli trials</a></p></li>
<li><p><a
href="https://www.programmingr.com/examples/neat-tricks/sample-r-function/r-rnorm/">R’s
rnorm – selecting values from a normal distribution</a></p></li>
<li><p><a
href="https://www.programmingr.com/examples/neat-tricks/sample-r-function/rexp/">R’s
exp – Simulating Exponential Distributions</a></p></li>
<li><p><a
href="https://aosmith.rbind.io/2018/08/29/getting-started-simulating-data/">Simulating
data in R</a></p></li>
</ul>
<p> </p>
<hr />
<p><font size="4">Información de la sesión</font></p>
<pre><code>## R version 4.1.1 (2021-08-10)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 20.04.2 LTS
## 
## Matrix products: default
## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
## 
## locale:
##  [1] LC_CTYPE=es_ES.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=es_CR.UTF-8        LC_COLLATE=es_ES.UTF-8    
##  [5] LC_MONETARY=es_CR.UTF-8    LC_MESSAGES=es_ES.UTF-8   
##  [7] LC_PAPER=es_CR.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=es_CR.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] car_3.1-0         carData_3.0-5     sjPlot_2.8.10     lmerTest_3.1-3   
##  [5] lme4_1.1-29       Matrix_1.3-4      viridis_0.6.2     viridisLite_0.4.0
##  [9] ggplot2_3.3.6     knitr_1.39        kableExtra_1.3.4 
## 
## loaded via a namespace (and not attached):
##  [1] httr_1.4.3          sass_0.4.1          tidyr_1.2.0        
##  [4] jsonlite_1.8.0      splines_4.1.1       modelr_0.1.8       
##  [7] bslib_0.3.1         datawizard_0.4.1    assertthat_0.2.1   
## [10] highr_0.9           yaml_2.3.5          bayestestR_0.12.1  
## [13] numDeriv_2016.8-1.1 pillar_1.8.0        backports_1.4.1    
## [16] lattice_0.20-44     glue_1.6.2          uuid_1.1-0         
## [19] digest_0.6.29       rvest_1.0.2         minqa_1.2.4        
## [22] colorspace_2.0-3    htmltools_0.5.3     pkgconfig_2.0.3    
## [25] broom_0.8.0         purrr_0.3.4         xtable_1.8-4       
## [28] mvtnorm_1.1-3       scales_1.2.0        webshot_0.5.3      
## [31] svglite_2.1.0       emmeans_1.7.4-1     tibble_3.1.8       
## [34] mgcv_1.8-36         farver_2.1.1        generics_0.1.2     
## [37] sjlabelled_1.2.0    withr_2.5.0         cli_3.3.0          
## [40] magrittr_2.0.3      effectsize_0.7.0    estimability_1.3   
## [43] evaluate_0.15       fansi_1.0.3         nlme_3.1-152       
## [46] MASS_7.3-54         xml2_1.3.3          tools_4.1.1        
## [49] formatR_1.12        lifecycle_1.0.1     stringr_1.4.0      
## [52] munsell_0.5.0       ggeffects_1.1.2     compiler_4.1.1     
## [55] jquerylib_0.1.4     systemfonts_1.0.4   rlang_1.0.4        
## [58] grid_4.1.1          nloptr_2.0.3        parameters_0.18.1  
## [61] rstudioapi_0.13     labeling_0.4.2      rmarkdown_2.14     
## [64] xaringanExtra_0.7.0 boot_1.3-28         gtable_0.3.0       
## [67] abind_1.4-5         sjstats_0.18.1      DBI_1.1.3          
## [70] sjmisc_2.8.9        R6_2.5.1            gridExtra_2.3      
## [73] dplyr_1.0.9         performance_0.9.0   fastmap_1.1.0      
## [76] utf8_1.2.2          insight_0.17.1      stringi_1.7.8      
## [79] Rcpp_1.0.9          vctrs_0.4.1         tidyselect_1.1.2   
## [82] xfun_0.31           coda_0.19-4</code></pre>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
